const WatetsuWatarasekeikokuCommon = {
    ...compNameWatetsu,
    lineName: 'わたらせ渓谷線',
    lineBack1: 'brown',
};

const WatetsuWatarasekeikoku = [
    {
        ekimeiKanj: '桐生',
        ekimeiKana: 'きりゅう',
        ekimeiRoma: 'Kiryū',
        sttnAddr: '群馬県桐生市末広町11-1',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '下新田',
        ekimeiKana: 'しもしんでん',
        ekimeiRoma: 'SHIMO-SHINDEN',
        sttnAddr: '群馬県桐生市相生町二丁目18-15',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '相老',
        ekimeiKana: 'あいおい',
        ekimeiRoma: 'AIOI',
        sttnAddr: '群馬県桐生市相生町二丁目756',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '運動公園',
        ekimeiKana: 'うんどうこうえん',
        ekimeiRoma: 'UNDÔ-KÔEN',
        sttnAddr: '群馬県桐生市相生町三丁目246',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '大間々',
        ekimeiKana: 'おおまま',
        ekimeiRoma: 'ÔMAMA',
        sttnAddr: '群馬県みどり市大間々町大間々1375',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '上神梅',
        ekimeiKana: 'かみかんばい',
        ekimeiRoma: 'KAMI-KAMBAI',
        sttnAddr: '群馬県みどり市大間々町上神梅245',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '本宿',
        ekimeiKana: 'もとじゅく',
        ekimeiRoma: 'MOTOJUKU',
        sttnAddr: '群馬県桐生市黒保根町宿廻1037-5',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '水沼',
        ekimeiKana: 'みずぬま',
        ekimeiRoma: 'MIZUNUMA',
        sttnAddr: '群馬県桐生市黒保根町水沼151',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '花輪',
        ekimeiKana: 'はなわ',
        ekimeiRoma: 'HANAWA',
        sttnAddr: '群馬県みどり市東町花輪99',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '中野',
        ekimeiKana: 'なかの',
        ekimeiRoma: 'NAKANO',
        sttnAddr: '群馬県みどり市東町花輪613-1',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '小中',
        ekimeiKana: 'こなか',
        ekimeiRoma: 'KONAKA',
        sttnAddr: '群馬県みどり市東町小中780',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '神戸',
        ekimeiKana: 'ごうど',
        ekimeiRoma: 'GÔDO',
        sttnAddr: '群馬県みどり市東町神戸891',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '沢入',
        ekimeiKana: 'そうり',
        ekimeiRoma: 'SÔRI',
        sttnAddr: '群馬県みどり市東町沢入962',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '原向',
        ekimeiKana: 'はらむこう',
        ekimeiRoma: 'HARAMUKÔ',
        sttnAddr: '栃木県日光市足尾町3066',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '通洞',
        ekimeiKana: 'つうどう',
        ekimeiRoma: 'TSÛDÔ',
        sttnAddr: '栃木県日光市足尾町松原13',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '足尾',
        ekimeiKana: 'あしお',
        ekimeiRoma: 'ASHIO',
        sttnAddr: '栃木県日光市足尾町掛水6',
        ...WatetsuWatarasekeikokuCommon,
    },
    {
        ekimeiKanj: '間藤',
        ekimeiKana: 'まとう',
        ekimeiRoma: 'MATÔ',
        sttnAddr: '栃木県日光市足尾町下間藤2',
        ...WatetsuWatarasekeikokuCommon,
    },
];
