const TokyometroGinzaCommon = {
    ...compNameTokyometro,
    lineName: '銀座線',
};

const TokyometroGinza = [
    {
        ekimeiKanj: '渋谷',
        ekimeiKana: 'しぶや',
        ekimeiRoma: 'Shibuya',
        sttnAddr: '東京都渋谷区渋谷二丁目21番1号',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '表参道',
        ekimeiKana: 'おもてさんどう',
        ekimeiRoma: 'Omote-sando',
        sttnAddr: '東京都港区北青山三丁目6-12',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '外苑前',
        ekimeiKana: 'がいえんまえ',
        ekimeiRoma: 'Gaiemmae',
        sttnAddr: '東京都港区北青山二丁目7-16',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '青山一丁目',
        ekimeiKana: 'あおやまいっちょうめ',
        ekimeiRoma: 'Aoyama-itchome',
        sttnAddr: '東京都港区南青山一丁目1-19',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '赤坂見附',
        ekimeiKana: 'あかさかみつけ',
        ekimeiRoma: 'Akasaka-mitsuke',
        sttnAddr: '東京都港区赤坂三丁目1-6',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '溜池山王',
        ekimeiKana: 'ためいけさんのう',
        ekimeiRoma: 'Tameike-sanno',
        sttnAddr: '東京都千代田区永田町二丁目11-1',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '虎ノ門',
        ekimeiKana: 'とらのもん',
        ekimeiRoma: 'Toranomon',
        sttnAddr: '東京都港区虎ノ門一丁目1-21',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '新橋',
        ekimeiKana: 'しんばし',
        ekimeiRoma: 'Shimbashi',
        sttnAddr: '東京都港区新橋二丁目17-5',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '銀座',
        ekimeiKana: 'ぎんざ',
        ekimeiRoma: 'Ginza',
        sttnAddr: '東京都中央区銀座四丁目1-2',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '京橋',
        ekimeiKana: 'きょうばし',
        ekimeiRoma: 'Kyobashi',
        sttnAddr: '東京都中央区京橋二丁目2-10',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '日本橋',
        ekimeiKana: 'にほんばし',
        ekimeiRoma: 'Nihombashi',
        sttnAddr: '東京都中央区日本橋一丁目3-11',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '三越前',
        ekimeiKana: 'みつこしまえ',
        ekimeiRoma: 'Mitsukoshimae',
        sttnAddr: '東京都中央区日本橋室町二丁目2-1',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '神田',
        ekimeiKana: 'かんだ',
        ekimeiRoma: 'Kanda',
        sttnAddr: '東京都千代田区神田須田町一丁目16',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '末広町',
        ekimeiKana: 'すえひろちょう',
        ekimeiRoma: 'Suehirocho',
        sttnAddr: '東京都千代田区外神田四丁目7-3',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '上野広小路',
        ekimeiKana: 'うえのひろこうじ',
        ekimeiRoma: 'Ueno-hirokoji',
        sttnAddr: '	東京都台東区上野三丁目29-3',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '上野',
        ekimeiKana: 'うえの',
        ekimeiRoma: 'Ueno',
        sttnAddr: '東京都台東区上野七丁目1-1',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '稲荷町',
        ekimeiKana: 'いなりちょう',
        ekimeiRoma: 'Inaricho',
        sttnAddr: '東京都台東区東上野三丁目33-11',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '田原町',
        ekimeiKana: 'たわらまち',
        ekimeiRoma: 'Tawaramachi',
        sttnAddr: '東京都台東区西浅草一丁目1-18',
        ...TokyometroGinzaCommon,
    },
    {
        ekimeiKanj: '浅草',
        ekimeiKana: 'あさくさ',
        ekimeiRoma: 'Asakusa',
        sttnAddr: '東京都台東区浅草一丁目1-3',
        ...TokyometroGinzaCommon,
    },
];
