const TokyometroFukutoshinCommon = {
    ...compNameTokyometro,
    lineName: '副都心線',
};

const TokyometroFukutoshin = [
    {
        ekimeiKanj: '和光市',
        ekimeiKana: 'わこうし',
        ekimeiRoma: 'Wakoshi',
        sttnAddr: '埼玉県和光市本町4-6',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '地下鉄成増',
        ekimeiKana: 'ちかてつなります',
        ekimeiRoma: 'Chikatetsu-narimasu',
        sttnAddr: '東京都板橋区成増二丁目11-3',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '地下鉄赤塚',
        ekimeiKana: 'ちかてつあかつか',
        ekimeiRoma: 'Chikatetsu-akatsuka',
        sttnAddr: '東京都練馬区北町八丁目37-16',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '平和台',
        ekimeiKana: 'へいわだい',
        ekimeiRoma: 'Heiwadai',
        sttnAddr: '東京都練馬区早宮二丁目17-48',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '氷川台',
        ekimeiKana: 'ひかわだい',
        ekimeiRoma: 'Hikawadai',
        sttnAddr: '東京都練馬区氷川台三丁目38-18',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '小竹向原',
        ekimeiKana: 'こたけむかいはら',
        ekimeiRoma: 'Kotake-mukaihara',
        sttnAddr: '東京都練馬区小竹町二丁目16-15',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '千川',
        ekimeiKana: 'せんかわ',
        ekimeiRoma: 'Senkawa',
        sttnAddr: '東京都豊島区要町三丁目10-7',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '要町',
        ekimeiKana: 'かなめちょう',
        ekimeiRoma: 'Kanamecho',
        sttnAddr: '	東京都豊島区要町一丁目1-10',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '池袋',
        ekimeiKana: 'いけぶくろ',
        ekimeiRoma: 'Ikebukuro',
        sttnAddr: '東京都豊島区西池袋三丁目28-14',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '雑司が谷',
        ekimeiKana: 'ぞうしがや',
        ekimeiRoma: 'Zoshigaya',
        sttnAddr: '東京都豊島区雑司が谷二丁目6-1',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '西早稲田',
        ekimeiKana: 'にしわせだ',
        ekimeiRoma: 'Nishi-waseda',
        sttnAddr: '東京都新宿区戸山三丁目18-2',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '東新宿',
        ekimeiKana: 'ひがししんじゅく',
        ekimeiRoma: 'Higashi-shinjuku',
        sttnAddr: '東京都新宿区新宿七丁目27-11',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '新宿三丁目',
        ekimeiKana: 'しんじゅくさんちょうめ',
        ekimeiRoma: 'Shinjuku-sanchome',
        sttnAddr: '東京都新宿区新宿五丁目18-22',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '北参道',
        ekimeiKana: 'きたさんどう',
        ekimeiRoma: 'Kita-sando',
        sttnAddr: '東京都渋谷区千駄ヶ谷四丁目7-11',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '明治神宮前〈原宿〉',
        ekimeiKana: 'めいじじんぐうまえ〈はらじゅく〉',
        ekimeiRoma: 'Meiji-jingumae‘Harajuku’',
        sttnAddr: '東京都渋谷区神宮前六丁目30-4',
        ...TokyometroFukutoshinCommon,
    },
    {
        ekimeiKanj: '渋谷',
        ekimeiKana: 'しぶや',
        ekimeiRoma: 'Shibuya',
        sttnAddr: '東京都渋谷区道玄坂二丁目1番1号',
        ...TokyometroFukutoshinCommon,
    },
];
