const TokyometroHibiyaCommon = {
    ...compNameTokyometro,
    lineName: '日比谷線',
};

const TokyometroHibiya = [
    {
        ekimeiKanj: '中目黒',
        ekimeiKana: 'なかめぐろ',
        ekimeiRoma: 'Naka-meguro',
        sttnAddr: '東京都目黒区上目黒三丁目4-1',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '恵比寿',
        ekimeiKana: 'えびす',
        ekimeiRoma: 'Ebisu',
        sttnAddr: '東京都渋谷区恵比寿南一丁目5-5',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '広尾',
        ekimeiKana: 'ひろお',
        ekimeiRoma: 'Hiro-o',
        sttnAddr: '東京都港区南麻布五丁目10-28',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '六本木',
        ekimeiKana: 'ろっぽんぎ',
        ekimeiRoma: 'Roppongi',
        sttnAddr: '東京都港区六本木六丁目1番25号',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '神谷町',
        ekimeiKana: 'かみやちょう',
        ekimeiRoma: 'Kamiyacho',
        sttnAddr: '東京都港区虎ノ門五丁目12-11',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '虎ノ門ヒルズ',
        ekimeiKana: 'とらのもんひるず',
        ekimeiRoma: 'Toranomon Hills',
        sttnAddr: '東京都港区虎ノ門一丁目22-12',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '霞ケ関',
        ekimeiKana: 'かすみがせき',
        ekimeiRoma: 'Kasumigaseki',
        sttnAddr: '東京都千代田区霞が関二丁目1-2',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '日比谷',
        ekimeiKana: 'ひびや',
        ekimeiRoma: 'Hibiya',
        sttnAddr: '東京都千代田区有楽町一丁目5-1',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '銀座',
        ekimeiKana: 'ぎんざ',
        ekimeiRoma: 'Ginza',
        sttnAddr: '東京都中央区銀座四丁目1-2',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '東銀座',
        ekimeiKana: 'ひがしぎんざ',
        ekimeiRoma: 'Higashi-ginza',
        sttnAddr: '東京都中央区銀座四丁目12-15',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '築地',
        ekimeiKana: 'つきじ',
        ekimeiRoma: 'Tsukiji',
        sttnAddr: '東京都中央区築地三丁目15-1',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '八丁堀',
        ekimeiKana: 'はっちょうぼり',
        ekimeiRoma: 'Hatchobori',
        sttnAddr: '東京都中央区八丁堀二丁目22-5',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '茅場町',
        ekimeiKana: 'かやばちょう',
        ekimeiRoma: 'Kayabacho',
        sttnAddr: '東京都中央区日本橋茅場町一丁目4-6',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '人形町',
        ekimeiKana: 'にんぎょうちょう',
        ekimeiRoma: 'Ningyocho',
        sttnAddr: '東京都中央区日本橋人形町二丁目6-5',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '小伝馬町',
        ekimeiKana: 'こでんまちょう',
        ekimeiRoma: 'Kodemmacho',
        sttnAddr: '東京都中央区日本橋小伝馬町11-1',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '秋葉原',
        ekimeiKana: 'あきはばら',
        ekimeiRoma: 'Akihabara',
        sttnAddr: '東京都千代田区神田佐久間町一丁目21',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '仲御徒町',
        ekimeiKana: 'なかおかちまち',
        ekimeiRoma: 'Naka-okachimachi',
        sttnAddr: '東京都台東区上野五丁目24-12',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '上野',
        ekimeiKana: 'うえの',
        ekimeiRoma: 'Ueno',
        sttnAddr: '東京都台東区東上野三丁目19-6',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '入谷',
        ekimeiKana: 'いりや',
        ekimeiRoma: 'Iriya',
        sttnAddr: '東京都台東区入谷一丁目6-4',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '三ノ輪',
        ekimeiKana: 'みのわ',
        ekimeiRoma: 'Minowa',
        sttnAddr: '東京都台東区三ノ輪二丁目14-7',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '南千住',
        ekimeiKana: 'みなみせんじゅ',
        ekimeiRoma: 'Minami-senju',
        sttnAddr: '東京都荒川区南千住四丁目3-1',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '北千住',
        ekimeiKana: 'きたせんじゅ',
        ekimeiRoma: 'Kita-senju',
        sttnAddr: '東京都足立区千住旭町42-1',
        ...TokyometroHibiyaCommon,
    },
];
