const TokyometroNanbokuCommon = {
    ...compNameTokyometro,
    lineName: '南北線',
    lineBack1: '#00ac9b',
};

const TokyometroNanboku = [
    {
        ekimeiKanj: '目黒',
        ekimeiKana: 'めぐろ',
        ekimeiRoma: 'Meguro',
        sttnAddr: '東京都品川区上大崎四丁目2-1',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '白金台',
        ekimeiKana: 'しろかねだい',
        ekimeiRoma: 'Shirokanedai',
        sttnAddr: '東京都港区白金台四丁目5-10',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '白金高輪',
        ekimeiKana: 'しろかねたかなわ',
        ekimeiRoma: 'Shirokane-takanawa',
        sttnAddr: '東京都港区高輪一丁目3-20',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '麻布十番',
        ekimeiKana: 'あざぶじゅうばん',
        ekimeiRoma: 'Azabu-juban',
        sttnAddr: '東京都港区麻布十番四丁目4-9',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '六本木一丁目',
        ekimeiKana: 'ろっぽんぎいっちょうめ',
        ekimeiRoma: 'Roppongi-itchome',
        sttnAddr: '東京都港区六本木一丁目4-1',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '溜池山王',
        ekimeiKana: 'ためいけさんのう',
        ekimeiRoma: 'Tameike-sanno',
        sttnAddr: '東京都千代田区永田町二丁目11-1',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '永田町',
        ekimeiKana: 'ながたちょう',
        ekimeiRoma: 'Nagatacho',
        sttnAddr: '東京都千代田区永田町一丁目11-28',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '四ツ谷',
        ekimeiKana: 'よつや',
        ekimeiRoma: 'Yotsuya',
        sttnAddr: '東京都新宿区四谷一丁目1',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '市ケ谷',
        ekimeiKana: 'いちがや',
        ekimeiRoma: 'Ichigaya',
        sttnAddr: '東京都新宿区市谷田町一丁目先',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '飯田橋',
        ekimeiKana: 'いいだばし',
        ekimeiRoma: 'Iidabashi',
        sttnAddr: '東京都新宿区神楽坂一丁目13',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '後楽園',
        ekimeiKana: 'こうらくえん',
        ekimeiRoma: 'Korakuen',
        sttnAddr: '東京都文京区春日一丁目2-3',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '東大前',
        ekimeiKana: 'とうだいまえ',
        ekimeiRoma: 'Todaimae',
        sttnAddr: '東京都文京区向丘一丁目19-2',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '本駒込',
        ekimeiKana: 'ほんこまごめ',
        ekimeiRoma: 'Hon-komagome',
        sttnAddr: '東京都文京区向丘二丁目37-1',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '駒込',
        ekimeiKana: 'こまごめ',
        ekimeiRoma: 'Komagome',
        sttnAddr: '東京都豊島区駒込二丁目1-40',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '西ケ原',
        ekimeiKana: 'にしがはら',
        ekimeiRoma: 'Nishigahara',
        sttnAddr: '東京都北区西ケ原二丁目3-8',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '王子',
        ekimeiKana: 'おうじ',
        ekimeiRoma: 'Oji',
        sttnAddr: '東京都北区王子一丁目10-18',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '王子神谷',
        ekimeiKana: 'おうじかみや',
        ekimeiRoma: 'Oji-kamiya',
        sttnAddr: '東京都北区王子五丁目2-11',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '志茂',
        ekimeiKana: 'しも',
        ekimeiRoma: 'Shimo',
        sttnAddr: '東京都北区志茂二丁目1-18',
        ...TokyometroNanbokuCommon,
    },
    {
        ekimeiKanj: '赤羽岩淵',
        ekimeiKana: 'あかばねいわぶち',
        ekimeiRoma: 'Akabane-iwabuchi',
        sttnAddr: '東京都北区赤羽一丁目52-8',
        ...TokyometroNanbokuCommon,
    },
];
