const TokyometroMarunouchiCommon = {
    ...compNameTokyometro,
    lineName: '丸ノ内線',
};

const TokyometroMarunouchi = [
    {
        ekimeiKanj: '荻窪',
        ekimeiKana: 'おぎくぼ',
        ekimeiRoma: 'Ogikubo',
        sttnAddr: '東京都杉並区荻窪五丁目31-7',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '南阿佐ケ谷',
        ekimeiKana: 'みなみあさがや',
        ekimeiRoma: 'Minami-asagaya',
        sttnAddr: '東京都杉並区阿佐谷南一丁目15-7',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '新高円寺',
        ekimeiKana: 'しんこうえんじ',
        ekimeiRoma: 'Shin-koenji',
        sttnAddr: '東京都杉並区高円寺南二丁目20-1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '東高円寺',
        ekimeiKana: 'ひがしこうえんじ',
        ekimeiRoma: 'Higashi-koenji',
        sttnAddr: '東京都杉並区和田三丁目55-42',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '新中野',
        ekimeiKana: 'しんなかの',
        ekimeiRoma: 'Shin-nakano',
        sttnAddr: '東京都中野区中央四丁目2-15',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '中野坂上',
        ekimeiKana: 'なかのさかうえ',
        ekimeiRoma: 'Nakano-sakaue',
        sttnAddr: '東京都中野区本町二丁目48-2',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '西新宿',
        ekimeiKana: 'にししんじゅく',
        ekimeiRoma: 'Nishi-shinjuku',
        sttnAddr: '東京都新宿区西新宿六丁目7-51',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '新宿',
        ekimeiKana: 'しんじゅく',
        ekimeiRoma: 'Shinjuku',
        sttnAddr: '東京都新宿区西新宿一丁目 西口地下街1号',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '新宿三丁目',
        ekimeiKana: 'しんじゅくさんちょうめ',
        ekimeiRoma: 'Shinjuku-sanchome',
        sttnAddr: '東京都新宿区新宿三丁目14-1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '新宿御苑前',
        ekimeiKana: 'しんじゅくぎょえんまえ',
        ekimeiRoma: 'Shinjuku-gyoemmae',
        sttnAddr: '東京都新宿区新宿一丁目8-1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '四谷三丁目',
        ekimeiKana: 'よつやさんちょうめ',
        ekimeiRoma: 'Yotsuya-sanchome',
        sttnAddr: '東京都新宿区四谷三丁目8',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '四ツ谷',
        ekimeiKana: 'よつや',
        ekimeiRoma: 'Yotsuya',
        sttnAddr: '東京都新宿区四谷一丁目1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '赤坂見附',
        ekimeiKana: 'あかさかみつけ',
        ekimeiRoma: 'Akasaka-mitsuke',
        sttnAddr: '東京都港区赤坂三丁目1-6',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '国会議事堂前',
        ekimeiKana: 'こっかいぎじどうまえ',
        ekimeiRoma: 'Kokkai-gijidomae',
        sttnAddr: '東京都千代田区永田町一丁目7-1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '霞ケ関',
        ekimeiKana: 'かすみがせき',
        ekimeiRoma: 'Kasumigaseki',
        sttnAddr: '東京都千代田区霞が関二丁目1-2',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '銀座',
        ekimeiKana: 'ぎんざ',
        ekimeiRoma: 'Ginza',
        sttnAddr: '東京都中央区銀座四丁目1-2',
        ...TokyometroHibiyaCommon,
    },
    {
        ekimeiKanj: '東京',
        ekimeiKana: 'とうきょう',
        ekimeiRoma: 'Tokyo',
        sttnAddr: '東京都千代田区丸の内一丁目6-5',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '大手町',
        ekimeiKana: 'おおてまち',
        ekimeiRoma: 'Otemachi',
        sttnAddr: '東京都千代田区',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '淡路町',
        ekimeiKana: 'あわじちょう',
        ekimeiRoma: 'Awajicho',
        sttnAddr: '東京都千代田区神田淡路町一丁目2',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '御茶ノ水',
        ekimeiKana: 'おちゃのみず',
        ekimeiRoma: 'Ochanomizu',
        sttnAddr: '東京都文京区湯島一丁目5-8',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '本郷三丁目',
        ekimeiKana: 'ほんごうさんちょうめ',
        ekimeiRoma: 'Hongo-sanchome',
        sttnAddr: '東京都文京区本郷二丁目39-1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '後楽園',
        ekimeiKana: 'こうらくえん',
        ekimeiRoma: 'Korakuen',
        sttnAddr: '東京都文京区春日一丁目2-3',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '茗荷谷',
        ekimeiKana: 'みょうがだに',
        ekimeiRoma: 'Myogadani',
        sttnAddr: '東京都文京区小日向四丁目6-15',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '新大塚',
        ekimeiKana: 'しんおおつか',
        ekimeiRoma: 'Shin-otsuka',
        sttnAddr: '東京都文京区大塚四丁目51-5',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '池袋',
        ekimeiKana: 'いけぶくろ',
        ekimeiRoma: 'Ikebukuro',
        sttnAddr: '東京都豊島区南池袋三丁目28-1',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '方南町',
        ekimeiKana: 'ほうなんちょう',
        ekimeiRoma: 'Honancho',
        sttnAddr: '東京都杉並区堀ノ内一丁目1番1号',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '中野富士見町',
        ekimeiKana: 'なかのふじみちょう',
        ekimeiRoma: 'Nakano-fujimicho',
        sttnAddr: '東京都中野区弥生町五丁目24-4',
        ...TokyometroMarunouchiCommon,
    },
    {
        ekimeiKanj: '中野新橋',
        ekimeiKana: 'なかのしんばし',
        ekimeiRoma: 'Nakano-shimbashi',
        sttnAddr: '東京都中野区弥生町二丁目26-8',
        ...TokyometroMarunouchiCommon,
    },
];
