const TokyometroChiyodaCommon = {
    ...compNameTokyometro,
    lineName: '千代田線',
};

const TokyometroChiyoda = [
    {
        ekimeiKanj: '代々木上原',
        ekimeiKana: 'よよぎうえはら',
        ekimeiRoma: 'Yoyogi-uehara',
        sttnAddr: '東京都渋谷区西原三丁目8番5号',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '代々木公園',
        ekimeiKana: 'よよぎこうえん',
        ekimeiRoma: 'Yoyogi-koen',
        sttnAddr: '東京都渋谷区富ヶ谷一丁目3-9',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '明治神宮前〈原宿〉',
        ekimeiKana: 'めいじじんぐうまえ〈はらじゅく〉',
        ekimeiRoma: 'Meiji-jingumae‘Harajuku’',
        sttnAddr: '東京都渋谷区神宮前一丁目18-22',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '表参道',
        ekimeiKana: 'おもてさんどう',
        ekimeiRoma: 'Omote-sando',
        sttnAddr: '東京都港区北青山三丁目6-12',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '乃木坂',
        ekimeiKana: 'のぎざか',
        ekimeiRoma: 'Nogizaka',
        sttnAddr: '東京都港区南青山一丁目25番8号',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '赤坂',
        ekimeiKana: 'あかさか',
        ekimeiRoma: 'Akasaka',
        sttnAddr: '東京都港区赤坂五丁目4-5',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '国会議事堂前',
        ekimeiKana: 'こっかいぎじどうまえ',
        ekimeiRoma: 'Kokkai-gijidomae',
        sttnAddr: '東京都千代田区永田町一丁目7-1',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '霞ケ関',
        ekimeiKana: 'かすみがせき',
        ekimeiRoma: 'Kasumigaseki',
        sttnAddr: '東京都千代田区霞が関二丁目1-2',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '日比谷',
        ekimeiKana: 'ひびや',
        ekimeiRoma: 'Hibiya',
        sttnAddr: '東京都千代田区有楽町一丁目5-1',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '二重橋前〈丸の内〉',
        ekimeiKana: 'にじゅうばしまえ〈まるのうち〉',
        ekimeiRoma: 'Nijubashimae‘Marunouchi’',
        sttnAddr: '東京都千代田区丸の内二丁目3-1',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '大手町',
        ekimeiKana: 'おおてまち',
        ekimeiRoma: 'Otemachi',
        sttnAddr: '東京都千代田区',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '新御茶ノ水',
        ekimeiKana: 'しんおちゃのみず',
        ekimeiRoma: 'Shin-ochanomizu',
        sttnAddr: '東京都千代田区神田駿河台三丁目先',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '湯島',
        ekimeiKana: 'ゆしま',
        ekimeiRoma: 'Yushima',
        sttnAddr: '	東京都文京区湯島三丁目47-10',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '根津',
        ekimeiKana: 'ねづ',
        ekimeiRoma: 'Nezu',
        sttnAddr: '東京都文京区根津一丁目3-5',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '千駄木',
        ekimeiKana: 'せんだぎ',
        ekimeiRoma: 'Sendagi',
        sttnAddr: '東京都文京区千駄木二丁目32-5',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '西日暮里',
        ekimeiKana: 'にしにっぽり',
        ekimeiRoma: 'Nishi-nippori',
        sttnAddr: '東京都荒川区西日暮里五丁目14-1',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '町屋',
        ekimeiKana: 'まちや',
        ekimeiRoma: 'Machiya',
        sttnAddr: '東京都荒川区町屋一丁目1-5',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '北千住',
        ekimeiKana: 'きたせんじゅ',
        ekimeiRoma: 'Kita-senju',
        sttnAddr: '東京都足立区千住二丁目63',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '綾瀬',
        ekimeiKana: 'あやせ',
        ekimeiRoma: 'Ayase',
        sttnAddr: '東京都足立区綾瀬三丁目1-1',
        ...TokyometroChiyodaCommon,
    },
    {
        ekimeiKanj: '北綾瀬',
        ekimeiKana: 'きたあやせ',
        ekimeiRoma: 'Kita-ayase',
        sttnAddr: '東京都足立区谷中二丁目6-21',
        ...TokyometroChiyodaCommon,
    },
];
