const TokyometroHanzoumonCommon = {
    ...compNameTokyometro,
    lineName: '半蔵門線',
};

const TokyometroHanzoumon = [
    {
        ekimeiKanj: '渋谷',
        ekimeiKana: 'しぶや',
        ekimeiRoma: 'Shibuya',
        sttnAddr: '東京都渋谷区道玄坂二丁目1番1号',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '表参道',
        ekimeiKana: 'おもてさんどう',
        ekimeiRoma: 'Omote-sando',
        sttnAddr: '東京都港区北青山三丁目6-12',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '青山一丁目',
        ekimeiKana: 'あおやまいっちょうめ',
        ekimeiRoma: 'Aoyama-itchome',
        sttnAddr: '東京都港区南青山一丁目1-19',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '永田町',
        ekimeiKana: 'ながたちょう',
        ekimeiRoma: 'Nagatacho',
        sttnAddr: '東京都千代田区永田町一丁目11-28',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '半蔵門',
        ekimeiKana: 'はんぞうもん',
        ekimeiRoma: 'Hanzomon',
        sttnAddr: '東京都千代田区麹町一丁目6',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '九段下',
        ekimeiKana: 'くだんした',
        ekimeiRoma: 'Kudanshita',
        sttnAddr: '東京都千代田区九段南一丁目6-1',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '神保町',
        ekimeiKana: 'じんぼうちょう',
        ekimeiRoma: 'Jimbocho',
        sttnAddr: '東京都千代田区神田神保町二丁目2番地',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '大手町',
        ekimeiKana: 'おおてまち',
        ekimeiRoma: 'Otemachi',
        sttnAddr: '東京都千代田区',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '三越前',
        ekimeiKana: 'みつこしまえ',
        ekimeiRoma: 'Mitsukoshimae',
        sttnAddr: '東京都中央区日本橋室町一丁目8-1',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '水天宮前',
        ekimeiKana: 'すいてんぐうまえ',
        ekimeiRoma: 'Suitengumae',
        sttnAddr: '東京都中央区日本橋蛎殻町二丁目1-1',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '清澄白河',
        ekimeiKana: 'きよすみしらかわ',
        ekimeiRoma: 'Kiyosumi-shirakawa',
        sttnAddr: '東京都江東区白河一丁目6-13',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '住吉',
        ekimeiKana: 'すみよし',
        ekimeiRoma: 'Sumiyoshi',
        sttnAddr: '東京都江東区猿江二丁目9-10',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '錦糸町',
        ekimeiKana: 'きんしちょう',
        ekimeiRoma: 'Kinshicho',
        sttnAddr: '東京都墨田区江東橋三丁目14-6',
        ...TokyometroHanzoumonCommon,
    },
    {
        ekimeiKanj: '押上〈スカイツリー前〉',
        ekimeiKana: 'おしあげ〈すかいつりーまえ〉',
        ekimeiRoma: 'Oshiage‘SKYTREE’',
        sttnAddr: '東京都墨田区押上一丁目1-65',
        ...TokyometroHanzoumonCommon,
    },
];
