const TokyometroTouzaiCommon = {
    ...compNameTokyometro,
    lineName: '東西線',
    lineBack1: '#009bbf',
};

const TokyometroTouzai = [
    {
        ekimeiKanj: '中野',
        ekimeiKana: 'なかの',
        ekimeiRoma: 'Nakano',
        sttnAddr: '東京都中野区中野五丁目31-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '落合',
        ekimeiKana: 'おちあい',
        ekimeiRoma: 'Ochiai',
        sttnAddr: '東京都新宿区上落合二丁目13-7',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '高田馬場',
        ekimeiKana: 'たかだのばば',
        ekimeiRoma: 'Takadanobaba',
        sttnAddr: '東京都新宿区高田馬場一丁目35-2',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '早稲田',
        ekimeiKana: 'わせだ',
        ekimeiRoma: 'Waseda',
        sttnAddr: '東京都新宿区早稲田南町12',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '神楽坂',
        ekimeiKana: 'かぐらざか',
        ekimeiRoma: 'Kagurazaka',
        sttnAddr: '東京都新宿区矢来町112',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '飯田橋',
        ekimeiKana: 'いいだばし',
        ekimeiRoma: 'Iidabashi',
        sttnAddr: '東京都千代田区飯田橋四丁目10-3',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '九段下',
        ekimeiKana: 'くだんした',
        ekimeiRoma: 'Kudanshita',
        sttnAddr: '東京都千代田区九段南一丁目6-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '竹橋',
        ekimeiKana: 'たけばし',
        ekimeiRoma: 'Takebashi',
        sttnAddr: '東京都千代田区一ツ橋一丁目1-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '大手町',
        ekimeiKana: 'おおてまち',
        ekimeiRoma: 'Otemachi',
        sttnAddr: '東京都千代田区',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '日本橋',
        ekimeiKana: 'にほんばし',
        ekimeiRoma: 'Nihombashi',
        sttnAddr: '東京都中央区日本橋一丁目3-11',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '茅場町',
        ekimeiKana: 'かやばちょう',
        ekimeiRoma: 'Kayabacho',
        sttnAddr: '東京都中央区日本橋茅場町一丁目4-6',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '門前仲町',
        ekimeiKana: 'もんぜんなかちょう',
        ekimeiRoma: 'Monzen-nakacho',
        sttnAddr: '東京都江東区門前仲町一丁目4-8',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '木場',
        ekimeiKana: 'きば',
        ekimeiRoma: 'Kiba',
        sttnAddr: '東京都江東区木場五丁目5-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '東陽町',
        ekimeiKana: 'とうようちょう',
        ekimeiRoma: 'Toyocho',
        sttnAddr: '東京都江東区東陽四丁目2-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '南砂町',
        ekimeiKana: 'みなみすなまち',
        ekimeiRoma: 'Minami-sunamachi',
        sttnAddr: '東京都江東区南砂三丁目11-85',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '西葛西',
        ekimeiKana: 'にしかさい',
        ekimeiRoma: 'Nishi-kasai',
        sttnAddr: '東京都江戸川区西葛西六丁目14-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '葛西',
        ekimeiKana: 'かさい',
        ekimeiRoma: 'Kasai',
        sttnAddr: '東京都江戸川区中葛西五丁目43-11',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '浦安',
        ekimeiKana: 'うらやす',
        ekimeiRoma: 'Urayasu',
        sttnAddr: '千葉県浦安市北栄１丁目13-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '南行徳',
        ekimeiKana: 'みなみぎょうとく',
        ekimeiRoma: 'Minami-gyotoku',
        sttnAddr: '千葉県市川市相之川4丁目17-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '行徳',
        ekimeiKana: 'ぎょうとく',
        ekimeiRoma: 'Gyotoku',
        sttnAddr: '千葉県市川市行徳駅前２丁目４-１',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '妙典',
        ekimeiKana: 'みょうでん',
        ekimeiRoma: 'Myoden',
        sttnAddr: '千葉県市川市富浜1丁目2-10',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '原木中山',
        ekimeiKana: 'ばらきなかやま',
        ekimeiRoma: 'Baraki-nakayama',
        sttnAddr: '千葉県船橋市本中山七丁目7-1',
        ...TokyometroTouzaiCommon,
    },
    {
        ekimeiKanj: '西船橋',
        ekimeiKana: 'にしふなばし',
        ekimeiRoma: 'Nishi-funabashi',
        sttnAddr: '千葉県船橋市西船四丁目27-7',
        ...TokyometroTouzaiCommon,
    },
];
