const TokyometroYuurakuchouCommon = {
    ...compNameTokyometro,
    lineName: '有楽町線',
    lineBack1: '#c1a470',
};

const TokyometroYuurakuchou = [
    {
        ekimeiKanj: '和光市',
        ekimeiKana: 'わこうし',
        ekimeiRoma: 'Wakoshi',
        sttnAddr: '埼玉県和光市本町4-6',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '地下鉄成増',
        ekimeiKana: 'ちかてつなります',
        ekimeiRoma: 'Chikatetsu-narimasu',
        sttnAddr: '東京都板橋区成増二丁目11-3',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '地下鉄赤塚',
        ekimeiKana: 'ちかてつあかつか',
        ekimeiRoma: 'Chikatetsu-akatsuka',
        sttnAddr: '東京都練馬区北町八丁目37-16',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '平和台',
        ekimeiKana: 'へいわだい',
        ekimeiRoma: 'Heiwadai',
        sttnAddr: '東京都練馬区早宮二丁目17-48',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '氷川台',
        ekimeiKana: 'ひかわだい',
        ekimeiRoma: 'Hikawadai',
        sttnAddr: '東京都練馬区氷川台三丁目38-18',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '小竹向原',
        ekimeiKana: 'こたけむかいはら',
        ekimeiRoma: 'Kotake-mukaihara',
        sttnAddr: '東京都練馬区小竹町二丁目16-15',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '千川',
        ekimeiKana: 'せんかわ',
        ekimeiRoma: 'Senkawa',
        sttnAddr: '東京都豊島区要町三丁目10-7',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '要町',
        ekimeiKana: 'かなめちょう',
        ekimeiRoma: 'Kanamecho',
        sttnAddr: '	東京都豊島区要町一丁目1-10',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '池袋',
        ekimeiKana: 'いけぶくろ',
        ekimeiRoma: 'Ikebukuro',
        sttnAddr: '東京都豊島区西池袋一丁目12-1',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '東池袋',
        ekimeiKana: 'ひがしいけぶくろ',
        ekimeiRoma: 'Higashi-ikebukuro',
        sttnAddr: '東京都豊島区東池袋四丁目4-4',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '護国寺',
        ekimeiKana: 'ごこくじ',
        ekimeiRoma: 'Gokokuji',
        sttnAddr: '東京都文京区大塚五丁目40-8',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '江戸川橋',
        ekimeiKana: 'えどがわばし',
        ekimeiRoma: 'Edogawabashi',
        sttnAddr: '東京都文京区関口一丁目19-6',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '飯田橋',
        ekimeiKana: 'いいだばし',
        ekimeiRoma: 'Iidabashi',
        sttnAddr: '東京都新宿区神楽坂一丁目13',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '市ケ谷',
        ekimeiKana: 'いちがや',
        ekimeiRoma: 'Ichigaya',
        sttnAddr: '東京都新宿区市谷田町一丁目先',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '麹町',
        ekimeiKana: 'こうじまち',
        ekimeiRoma: 'Kojimachi',
        sttnAddr: '東京都千代田区麹町三丁目2',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '永田町',
        ekimeiKana: 'ながたちょう',
        ekimeiRoma: 'Nagatacho',
        sttnAddr: '東京都千代田区永田町一丁目11-28',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '桜田門',
        ekimeiKana: 'さくらだもん',
        ekimeiRoma: 'Sakuradamon',
        sttnAddr: '東京都千代田区霞が関二丁目1-1',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '有楽町',
        ekimeiKana: 'ゆうらくちょう',
        ekimeiRoma: 'Yurakucho',
        sttnAddr: '東京都千代田区有楽町一丁目11-1',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '銀座一丁目',
        ekimeiKana: 'ぎんざいっちょうめ',
        ekimeiRoma: 'Ginza-itchome',
        sttnAddr: '東京都中央区銀座一丁目7-12',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '新富町',
        ekimeiKana: 'しんとみちょう',
        ekimeiRoma: 'Shintomicho',
        sttnAddr: '東京都中央区築地一丁目1-1',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '月島',
        ekimeiKana: 'つきしま',
        ekimeiRoma: 'Tsukishima',
        sttnAddr: '東京都中央区月島一丁目3番9号',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '豊洲',
        ekimeiKana: 'とよす',
        ekimeiRoma: 'Toyosu',
        sttnAddr: '東京都江東区豊洲四丁目1-1',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '辰巳',
        ekimeiKana: 'たつみ',
        ekimeiRoma: 'Tatsumi',
        sttnAddr: '東京都江東区辰巳一丁目1-44',
        ...TokyometroYuurakuchouCommon,
    },
    {
        ekimeiKanj: '新木場',
        ekimeiKana: 'しんきば',
        ekimeiRoma: 'Shin-kiba',
        sttnAddr: '東京都江東区新木場一丁目6',
        ...TokyometroYuurakuchouCommon,
    },
];
