const JreSotobouCommon = {
    ...compNameJre,
    lineName: '外房線',
}

const JreSotobou = [
    {
        ekimeiKanj: '千葉',
        ekimeiKana: 'ちば',
        ekimeiRoma: 'Chiba',
        sttnAddr: '千葉市中央区新千葉一丁目1-1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '本千葉',
        ekimeiKana: 'ほんちば',
        ekimeiRoma: 'Hon-Chiba',
        sttnAddr: '千葉市中央区長洲一丁目30-1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '蘇我',
        ekimeiKana: 'そが',
        ekimeiRoma: 'Soga',
        sttnAddr: '千葉市中央区今井二丁目50-2',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '鎌取',
        ekimeiKana: 'かまとり',
        ekimeiRoma: 'Kamatori',
        sttnAddr: '千葉市緑区鎌取町787-3',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '誉田',
        ekimeiKana: 'ほんだ',
        ekimeiRoma: 'Honda',
        sttnAddr: '千葉市緑区誉田町二丁目24',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '土気',
        ekimeiKana: 'とけ',
        ekimeiRoma: 'Toke',
        sttnAddr: '千葉市緑区土気町1727-1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '大網',
        ekimeiKana: 'おおあみ',
        ekimeiRoma: 'Ōami',
        sttnAddr: '千葉県大網白里市南玉21-7',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '永田',
        ekimeiKana: 'ながた',
        ekimeiRoma: 'Nagata',
        sttnAddr: '千葉県大網白里市永田1835',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '本納',
        ekimeiKana: 'ほんのう',
        ekimeiRoma: 'Honnō',
        sttnAddr: '千葉県茂原市本納1791',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '新茂原',
        ekimeiKana: 'しんもばら',
        ekimeiRoma: 'Shim-Mobara',
        sttnAddr: '千葉県茂原市長尾2667',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '茂原',
        ekimeiKana: 'もばら',
        ekimeiRoma: 'Mobara',
        sttnAddr: '千葉県茂原市町保1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '八積',
        ekimeiKana: 'やつみ',
        ekimeiRoma: 'Yatsumi',
        sttnAddr: '千葉県長生郡長生村岩沼822',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '',
        ekimeiKana: '',
        ekimeiRoma: '',
        sttnAddr: '',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '',
        ekimeiKana: '',
        ekimeiRoma: '',
        sttnAddr: '',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '',
        ekimeiKana: '',
        ekimeiRoma: '',
        sttnAddr: '',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '',
        ekimeiKana: '',
        ekimeiRoma: '',
        sttnAddr: '',
        ...JreSotobouCommon,
    },
];
