const JreSotobouCommon = {
    ...compNameJre,
    lineName: '外房線',
}

const JreSotobou = [
    {
        ekimeiKanj: '千葉',
        ekimeiKana: 'ちば',
        ekimeiRoma: 'Chiba',
        sttnAddr: '千葉市中央区新千葉一丁目1-1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '本千葉',
        ekimeiKana: 'ほんちば',
        ekimeiRoma: 'Hon-Chiba',
        sttnAddr: '千葉市中央区長洲一丁目30-1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '蘇我',
        ekimeiKana: 'そが',
        ekimeiRoma: 'Soga',
        sttnAddr: '千葉市中央区今井二丁目50-2',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '鎌取',
        ekimeiKana: 'かまとり',
        ekimeiRoma: 'Kamatori',
        sttnAddr: '千葉市緑区鎌取町787-3',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '誉田',
        ekimeiKana: 'ほんだ',
        ekimeiRoma: 'Honda',
        sttnAddr: '千葉市緑区誉田町二丁目24',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '土気',
        ekimeiKana: 'とけ',
        ekimeiRoma: 'Toke',
        sttnAddr: '千葉市緑区土気町1727-1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '大網',
        ekimeiKana: 'おおあみ',
        ekimeiRoma: 'Ōami',
        sttnAddr: '千葉県大網白里市南玉21-7',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '永田',
        ekimeiKana: 'ながた',
        ekimeiRoma: 'Nagata',
        sttnAddr: '千葉県大網白里市永田1835',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '本納',
        ekimeiKana: 'ほんのう',
        ekimeiRoma: 'Honnō',
        sttnAddr: '千葉県茂原市本納1791',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '新茂原',
        ekimeiKana: 'しんもばら',
        ekimeiRoma: 'Shim-Mobara',
        sttnAddr: '千葉県茂原市長尾2667',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '茂原',
        ekimeiKana: 'もばら',
        ekimeiRoma: 'Mobara',
        sttnAddr: '千葉県茂原市町保1',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '八積',
        ekimeiKana: 'やつみ',
        ekimeiRoma: 'Yatsumi',
        sttnAddr: '千葉県長生郡長生村岩沼822',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '上総一ノ宮',
        ekimeiKana: 'かずさいちのみや',
        ekimeiRoma: 'Kazusa-Ichinomiya',
        sttnAddr: '千葉県長生郡一宮町一宮2640-2',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '東浪見',
        ekimeiKana: 'とらみ',
        ekimeiRoma: 'Torami',
        sttnAddr: '千葉県長生郡一宮町東浪見',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '太東',
        ekimeiKana: 'たいとう',
        ekimeiRoma: 'Taitō',
        sttnAddr: '千葉県いすみ市岬町椎木304-3',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '長者町',
        ekimeiKana: 'ちょうじゃまち',
        ekimeiRoma: 'Chōjamachi',
        sttnAddr: '千葉県いすみ市岬町長者81',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '三門',
        ekimeiKana: 'みかど',
        ekimeiRoma: 'Mikado',
        sttnAddr: '千葉県いすみ市日在2425',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '大原',
        ekimeiKana: 'おおはら',
        ekimeiRoma: 'Ōhara',
        sttnAddr: '千葉県いすみ市大原8701',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '浪花',
        ekimeiKana: 'なみはな',
        ekimeiRoma: 'Namihana',
        sttnAddr: '千葉県いすみ市小沢1456',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '御宿',
        ekimeiKana: 'おんじゅく',
        ekimeiRoma: 'Onjuku',
        sttnAddr: '千葉県夷隅郡御宿町須賀195',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '勝浦',
        ekimeiKana: 'かつうら',
        ekimeiRoma: 'Katsuura',
        sttnAddr: '千葉県勝浦市墨名254',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '鵜原',
        ekimeiKana: 'うばら',
        ekimeiRoma: 'Ubara',
        sttnAddr: '千葉県勝浦市鵜原1664',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '上総興津',
        ekimeiKana: 'かずさおきつ',
        ekimeiRoma: 'Kazusa-Okitsu',
        sttnAddr: '千葉県勝浦市興津307-6',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '行川アイランド',
        ekimeiKana: 'なめがわあいらんど',
        ekimeiRoma: 'Namegawa-Island',
        sttnAddr: '	千葉県勝浦市浜行川',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '安房小湊',
        ekimeiKana: 'あわこみなと',
        ekimeiRoma: 'Awa-Kominato',
        sttnAddr: '千葉県鴨川市内浦403',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '安房天津',
        ekimeiKana: 'あわあまつ',
        ekimeiRoma: 'Awa-Amatsu',
        sttnAddr: '千葉県鴨川市天津1016',
        ...JreSotobouCommon,
    },
    {
        ekimeiKanj: '安房鴨川',
        ekimeiKana: 'あわかもがわ',
        ekimeiRoma: 'Awa-Kamogawa',
        sttnAddr: '千葉県鴨川市横渚952',
        ...JreSotobouCommon,
    },
];
