const JreUchibouCommon = {
    ...compNameJre,
    lineName: '内房線',
}

const JreUchibou = [
    {
        ekimeiKanj: '千葉',
        ekimeiKana: 'ちば',
        ekimeiRoma: 'Chiba',
        sttnAddr: '千葉市中央区新千葉一丁目1-1',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '本千葉',
        ekimeiKana: 'ほんちば',
        ekimeiRoma: 'Hon-Chiba',
        sttnAddr: '千葉市中央区長洲一丁目30-1',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '蘇我',
        ekimeiKana: 'そが',
        ekimeiRoma: 'Soga',
        sttnAddr: '千葉市中央区今井二丁目50-2',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '浜野',
        ekimeiKana: 'はまの',
        ekimeiRoma: 'Hamano',
        sttnAddr: '千葉市中央区村田町700',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '八幡宿',
        ekimeiKana: 'やわたじゅく',
        ekimeiRoma: 'Yawatajuku',
        sttnAddr: '千葉県市原市八幡930-3',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '五井',
        ekimeiKana: 'ごい',
        ekimeiRoma: 'Goi',
        sttnAddr: '千葉県市原市五井中央西二丁目1-11',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '姉ケ崎',
        ekimeiKana: 'あねがさき',
        ekimeiRoma: 'Anegasaki',
        sttnAddr: '千葉県市原市姉崎東',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '長浦',
        ekimeiKana: 'ながうら',
        ekimeiRoma: 'Nagaura',
        sttnAddr: '千葉県袖ケ浦市蔵波5',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '袖ケ浦',
        ekimeiKana: 'そでがうら',
        ekimeiRoma: 'Sodegaura',
        sttnAddr: '千葉県袖ケ浦市奈良輪1198',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '巌根',
        ekimeiKana: 'いわね',
        ekimeiRoma: 'Iwane',
        sttnAddr: '千葉県木更津市岩根三丁目5-1',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '木更津',
        ekimeiKana: 'きさらづ',
        ekimeiRoma: 'Kisarazu',
        sttnAddr: '千葉県木更津市富士見一丁目1-1',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '君津',
        ekimeiKana: 'きみつ',
        ekimeiRoma: 'Kimitsu',
        sttnAddr: '千葉県君津市東坂田一丁目1-1',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '青堀',
        ekimeiKana: 'あおほり',
        ekimeiRoma: 'Aohori',
        sttnAddr: '千葉県富津市大堀1884',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '大貫',
        ekimeiKana: 'おおぬき',
        ekimeiRoma: 'Ōnuki',
        sttnAddr: '千葉県富津市千種新田364-3',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '佐貫町',
        ekimeiKana: 'さぬきまち',
        ekimeiRoma: 'Sanukimachi',
        sttnAddr: '千葉県富津市亀田540-2',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '上総湊',
        ekimeiKana: 'かずさみなと',
        ekimeiRoma: 'Kazusa-Minato',
        sttnAddr: '千葉県富津市湊736',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '',
        ekimeiKana: '',
        ekimeiRoma: '',
        sttnAddr: '',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '',
        ekimeiKana: '',
        ekimeiRoma: '',
        sttnAddr: '',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '安房鴨川',
        ekimeiKana: 'あわかもがわ',
        ekimeiRoma: 'Awa-Kamogawa',
        sttnAddr: '千葉県鴨川市横渚952',
        ...JreUchibouCommon,
    },
];
