const JoudenBesshoCommon = {
    ...compNameJouden,
    lineName: '別所線',
    passArea: '["ShuP"]',
};

const JoudenBessho = [
    {
        ekimeiKanj: '上田',
        ekimeiKana: 'うえだ',
        ekimeiRoma: 'Ueda',
        sttnAddr: '長野県上田市天神一丁目1-1',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '城下',
        ekimeiKana: 'しろした',
        ekimeiRoma: 'Shiroshita',
        sttnAddr: '長野県上田市諏訪形字中田982',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '三好町',
        ekimeiKana: 'みよしちょう',
        ekimeiRoma: 'Miyoshicho',
        sttnAddr: '長野県上田市御所字中満丁245',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '赤坂上',
        ekimeiKana: 'あかさかうえ',
        ekimeiRoma: 'Akasakaue',
        sttnAddr: '長野県上田市上田原字一ノ口875-7',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '上田原',
        ekimeiKana: 'うえだはら',
        ekimeiRoma: 'Uedahara',
        sttnAddr: '長野県上田市上田原字屋鋪田697-5',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '寺下',
        ekimeiKana: 'てらした',
        ekimeiRoma: 'Terashita',
        sttnAddr: '長野県上田市神畑字寺下616-1',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '神畑',
        ekimeiKana: 'かばたけ',
        ekimeiRoma: 'Kabatake',
        sttnAddr: '長野県上田市神畑字孤池94-5',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '大学前',
        ekimeiKana: 'だいがくまえ',
        ekimeiRoma: 'Daigakumae',
        sttnAddr: '長野県上田市下之郷字上迎284-5',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '下之郷',
        ekimeiKana: 'しものごう',
        ekimeiRoma: 'Shimonogo',
        sttnAddr: '長野県上田市大字下之郷517-3',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '中塩田',
        ekimeiKana: 'なかしおだ',
        ekimeiRoma: 'Nakashioda',
        sttnAddr: '長野県上田市五加字富在家1225-6',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '塩田町',
        ekimeiKana: 'しおだまち',
        ekimeiRoma: 'Shiodamachi',
        sttnAddr: '長野県上田市中野字兼田40-2',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '中野',
        ekimeiKana: 'なかの',
        ekimeiRoma: 'Nakano',
        sttnAddr: '長野県上田市中野字池下496-4',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '舞田',
        ekimeiKana: 'まいた',
        ekimeiRoma: 'Maita',
        sttnAddr: '長野県上田市舞田字柳堂44-6',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '八木沢',
        ekimeiKana: 'やぎさわ',
        ekimeiRoma: 'Yagisawa',
        sttnAddr: '長野県上田市八木沢字表田中439-2',
        ...JoudenBesshoCommon,
    },
    {
        ekimeiKanj: '別所温泉',
        ekimeiKana: 'べっしょおんせん',
        ekimeiRoma: 'Bessho-onsen',
        sttnAddr: '長野県上田市別所温泉字分去1853-3',
        ...JoudenBesshoCommon,
    },
];
