const FujikyurailwayFujikyuukouCommon = {
    ...compNameFujikyurailway,
    lineName: '富士急行線',
    passArea: '["ShuP"]',
};

const FujikyurailwayFujikyuukou = [
    {
        ekimeiKanj: '大月',
        ekimeiKana: 'おおつき',
        ekimeiRoma: 'Otsuki',
        sttnAddr: '	山梨県大月市大月一丁目1-1',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '上大月',
        ekimeiKana: 'かみおおつき',
        ekimeiRoma: 'KAMIOTSUKI',
        sttnAddr: '山梨県大月市大月二丁目223-3',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '田野倉',
        ekimeiKana: 'たのくら',
        ekimeiRoma: 'TANOKURA',
        sttnAddr: '山梨県都留市田野倉771',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '禾生',
        ekimeiKana: 'かせい',
        ekimeiRoma: 'KASEI',
        sttnAddr: '山梨県都留市古川渡524-3',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '赤坂',
        ekimeiKana: 'あかさか',
        ekimeiRoma: 'AKASAKA',
        sttnAddr: '山梨県都留市四日市場87-2',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '都留市',
        ekimeiKana: 'つるし',
        ekimeiRoma: 'TSURUSHI',
        sttnAddr: '山梨県都留市つる一丁目12-1',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '谷村町',
        ekimeiKana: 'やむらまち',
        ekimeiRoma: 'YAMURAMACHI',
        sttnAddr: '山梨県都留市上谷一丁目2-8',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '都留文科大学前',
        ekimeiKana: 'つるぶんかだいがくまえ',
        ekimeiRoma: 'TSURUBUNKADAIGAKU-MAE',
        sttnAddr: '山梨県都留市田原二丁目7番12号',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '十日市場',
        ekimeiKana: 'とおかいちば',
        ekimeiRoma: 'TOKAICHIBA',
        sttnAddr: '山梨県都留市十日市場769-3',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '東桂',
        ekimeiKana: 'ひがしかつら',
        ekimeiRoma: 'HIGASHIKATSURA',
        sttnAddr: '山梨県都留市桂町1380',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '三つ峠',
        ekimeiKana: 'みつとうげ',
        ekimeiRoma: 'MITSUTOGE',
        sttnAddr: '山梨県南都留郡西桂町小沼1583',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '寿',
        ekimeiKana: 'ことぶき',
        ekimeiRoma: 'KOTOBUKI',
        sttnAddr: '山梨県富士吉田市上暮地字尾垂2930番地2',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '葭池温泉前',
        ekimeiKana: 'よしいけおんせんまえ',
        ekimeiRoma: 'YOSHIIKEONSEN-MAE',
        sttnAddr: '山梨県富士吉田市富士見四丁目8番24号',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '下吉田',
        ekimeiKana: 'しもよしだ',
        ekimeiRoma: 'SHIMOYOSHIDA',
        sttnAddr: '山梨県富士吉田市新町二丁目8番12号',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '月江寺',
        ekimeiKana: 'げっこうじ',
        ekimeiRoma: 'GEKKOJI',
        sttnAddr: '山梨県富士吉田市緑ケ丘一丁目1番14号',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '富士山',
        ekimeiKana: 'ふじさん',
        ekimeiRoma: 'Mt. FUJI',
        sttnAddr: '山梨県富士吉田市上吉田二丁目5番1号',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '富士急ハイランド',
        ekimeiKana: 'ふじきゅうハイランド',
        ekimeiRoma: 'FUJIKYU-HIGHLAND',
        sttnAddr: '山梨県南都留郡富士河口湖町船津6663',
        ...FujikyurailwayFujikyuukouCommon,
    },
    {
        ekimeiKanj: '河口湖',
        ekimeiKana: 'かわぐちこ',
        ekimeiRoma: 'KAWAGUCHIKO',
        sttnAddr: '山梨県南都留郡富士河口湖町船津3641',
        ...FujikyurailwayFujikyuukouCommon,
    },
];
