const KeioKeiouCommon = {
    ...compNameKeio,
    lineName: '京王線',
};

const KeioKeiou = [
    {
        ekimeiKanj: '新宿',
        ekimeiKana: 'しんじゅく',
        ekimeiRoma: 'Shinjuku',
        sttnAddr: '東京都新宿区西新宿一丁目1-4',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '笹塚',
        ekimeiKana: 'ささづか',
        ekimeiRoma: 'Sasazuka',
        sttnAddr: '東京都渋谷区笹塚一丁目56番7号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '代田橋',
        ekimeiKana: 'だいたばし',
        ekimeiRoma: 'Daitabashi',
        sttnAddr: '東京都世田谷区大原二丁目18番9号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '明大前',
        ekimeiKana: 'めいだいまえ',
        ekimeiRoma: 'Meidaimae',
        sttnAddr: '東京都世田谷区松原二丁目45番1号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '下高井戸',
        ekimeiKana: 'しもたかいど',
        ekimeiRoma: 'Shimo-takaido',
        sttnAddr: '東京都世田谷区松原三丁目29番17号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '桜上水',
        ekimeiKana: 'さくらじょうすい',
        ekimeiRoma: 'Sakurajōsui',
        sttnAddr: '東京都世田谷区桜上水五丁目29番52号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '上北沢',
        ekimeiKana: 'かみきたざわ',
        ekimeiRoma: 'Kami-kitazawa',
        sttnAddr: '東京都世田谷区上北沢四丁目14番3号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '八幡山',
        ekimeiKana: 'はちまんやま',
        ekimeiRoma: 'Hachiman-yama',
        sttnAddr: '	東京都杉並区上高井戸一丁目1番11号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '芦花公園',
        ekimeiKana: 'ろかこうえん',
        ekimeiRoma: 'Roka-kōen',
        sttnAddr: '東京都世田谷区南烏山三丁目1番16号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '千歳烏山',
        ekimeiKana: 'ちとせからすやま',
        ekimeiRoma: 'Chitose-karasuyama',
        sttnAddr: '東京都世田谷区南烏山六丁目1番1号',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '仙川',
        ekimeiKana: 'せんがわ',
        ekimeiRoma: 'Sengawa',
        sttnAddr: '東京都調布市仙川町一丁目43番地',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: 'つつじヶ丘',
        ekimeiKana: 'つつじがおか',
        ekimeiRoma: 'Tsutsujigaoka',
        sttnAddr: '東京都調布市西つつじケ丘三丁目35番地1',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '柴崎',
        ekimeiKana: 'しばさき',
        ekimeiRoma: 'Shibasaki',
        sttnAddr: '東京都調布市菊野台二丁目67番地11',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '国領',
        ekimeiKana: 'こくりょう',
        ekimeiRoma: 'Kokuryō',
        sttnAddr: '東京都調布市国領町三丁目18番地1',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '布田',
        ekimeiKana: 'ふだ',
        ekimeiRoma: 'Fuda',
        sttnAddr: '東京都調布市国領町五丁目67番地1',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '調布',
        ekimeiKana: 'ちょうふ',
        ekimeiRoma: 'Chōfu',
        sttnAddr: '東京都調布市布田四丁目32番地1',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '調布',
        ekimeiKana: 'ちょうふ',
        ekimeiRoma: 'Chōfu',
        sttnAddr: '東京都調布市布田四丁目32番地1',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '西調布',
        ekimeiKana: 'にしちょうふ',
        ekimeiRoma: 'Nishi-chōfu',
        sttnAddr: '東京都調布市上石原一丁目25-17',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '飛田給',
        ekimeiKana: 'とびたきゅう',
        ekimeiRoma: 'Tobitakyū',
        sttnAddr: '東京都調布市飛田給一丁目42-11',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '武蔵野台',
        ekimeiKana: 'むさしのだい',
        ekimeiRoma: 'Musashinodai',
        sttnAddr: '東京都府中市白糸台四丁目18-4',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '多磨霊園',
        ekimeiKana: 'たまれいえん',
        ekimeiRoma: 'Tama-reien',
        sttnAddr: '東京都府中市清水が丘三丁目26-11',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '東府中',
        ekimeiKana: 'ひがしふちゅう',
        ekimeiRoma: 'Higashi-fuchū',
        sttnAddr: '東京都府中市清水が丘一丁目8-3',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '府中',
        ekimeiKana: 'ふちゅう',
        ekimeiRoma: 'Fuchū',
        sttnAddr: '東京都府中市宮町一丁目1-10',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '分倍河原',
        ekimeiKana: 'ぶばいがわら',
        ekimeiRoma: 'Bubaigawara',
        sttnAddr: '東京都府中市片町二丁目21-18',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '中河原',
        ekimeiKana: 'なかがわら',
        ekimeiRoma: 'Nakagawara',
        sttnAddr: '東京都府中市住吉町二丁目1-16',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '聖蹟桜ヶ丘',
        ekimeiKana: 'せいせきさくらがおか',
        ekimeiRoma: 'Seiseki-sakuragaoka',
        sttnAddr: '東京都多摩市関戸一丁目10-10',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '百草園',
        ekimeiKana: 'もぐさえん',
        ekimeiRoma: 'Mogusaen',
        sttnAddr: '東京都日野市百草209',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '高幡不動',
        ekimeiKana: 'たかはたふどう',
        ekimeiRoma: 'Takahatafudō',
        sttnAddr: '東京都日野市高幡139番地',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '南平',
        ekimeiKana: 'みなみだいら',
        ekimeiRoma: 'Minamidaira',
        sttnAddr: '東京都日野市南平六丁目9-31',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '平山城址公園',
        ekimeiKana: 'ひらやまじょうしこうえん',
        ekimeiRoma: 'Hirayamajōshi-kōen',
        sttnAddr: '東京都日野市平山五丁目18-10',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '長沼',
        ekimeiKana: 'ながぬま',
        ekimeiRoma: 'Naganuma',
        sttnAddr: '東京都八王子市長沼町700',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '北野',
        ekimeiKana: 'きたの',
        ekimeiRoma: 'Kitano',
        sttnAddr: '東京都八王子市打越町335-1',
        ...KeioKeiouCommon,
    },
    {
        ekimeiKanj: '京王八王子',
        ekimeiKana: 'けいおうはちおうじ',
        ekimeiRoma: 'Keiō-hachiōji',
        sttnAddr: '東京都八王子市明神町三丁目27番1号',
        ...KeioKeiouCommon,
    },
];
