const KeioInokashiraCommon = {
    ...compNameKeio,
    lineName: '井の頭線',
};

const KeioInokashira = [
    {
        ekimeiKanj: '渋谷',
        ekimeiKana: 'しぶや',
        ekimeiRoma: 'Shibuya',
        sttnAddr: '東京都渋谷区道玄坂一丁目4番1号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '神泉',
        ekimeiKana: 'しんせん',
        ekimeiRoma: 'Shinsen',
        sttnAddr: '東京都渋谷区神泉町4番6号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '駒場東大前',
        ekimeiKana: 'こまばとうだいまえ',
        ekimeiRoma: 'Komaba-tōdaimae',
        sttnAddr: '東京都目黒区駒場三丁目9番1号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '池ノ上',
        ekimeiKana: 'いけのうえ',
        ekimeiRoma: 'Ikenoue',
        sttnAddr: '東京都世田谷区代沢二丁目43番8号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '下北沢',
        ekimeiKana: 'しもきたざわ',
        ekimeiRoma: 'Shimo-kitazawa',
        sttnAddr: '東京都世田谷区北沢2丁目23番9号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '新代田',
        ekimeiKana: 'しんだいた',
        ekimeiRoma: 'Shindaita',
        sttnAddr: '東京都世田谷区代田五丁目30番18号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '東松原',
        ekimeiKana: 'ひがしまつばら',
        ekimeiRoma: 'Higashi-matsubara',
        sttnAddr: '東京都世田谷区松原五丁目2番6号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '明大前',
        ekimeiKana: 'めいだいまえ',
        ekimeiRoma: 'Meidaimae',
        sttnAddr: '東京都世田谷区松原二丁目45番1号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '永福町',
        ekimeiKana: 'えいふくちょう',
        ekimeiRoma: 'Eifukuchō',
        sttnAddr: '東京都杉並区永福二丁目60番31号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '西永福',
        ekimeiKana: 'にしえいふく',
        ekimeiRoma: 'Nishi-eifuku',
        sttnAddr: '	東京都杉並区永福三丁目36番1号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '浜田山',
        ekimeiKana: 'はまだやま',
        ekimeiRoma: 'Hamadayama',
        sttnAddr: '東京都杉並区浜田山三丁目31番2号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '高井戸',
        ekimeiKana: 'たかいど',
        ekimeiRoma: 'Takaido',
        sttnAddr: '東京都杉並区高井戸西二丁目1番26号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '富士見ヶ丘',
        ekimeiKana: 'ふじみがおか',
        ekimeiRoma: 'Fujimigaoka',
        sttnAddr: '東京都杉並区久我山五丁目1番25号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '久我山',
        ekimeiKana: 'くがやま',
        ekimeiRoma: 'Kugayama',
        sttnAddr: '東京都杉並区久我山四丁目1番11号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '三鷹台',
        ekimeiKana: 'みたかだい',
        ekimeiRoma: 'Mitakadai',
        sttnAddr: '東京都三鷹市井の頭一丁目32番1号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '井の頭公園',
        ekimeiKana: 'いのかしらこうえん',
        ekimeiRoma: 'Inokashira-kōen',
        sttnAddr: '東京都三鷹市井の頭三丁目35番12号',
        ...KeioInokashiraCommon,
    },
    {
        ekimeiKanj: '吉祥寺',
        ekimeiKana: 'きちじょうじ',
        ekimeiRoma: 'Kichijōji',
        sttnAddr: '東京都武蔵野市吉祥寺南町二丁目1番25号',
        ...KeioInokashiraCommon,
    },
];
