const CtkChichibuhonCommon = {
    ...compNameCtk,
    lineName: '秩父本線',
    lineBack1: '#0000ff',
};

const CtkChichibuhonCommon1 = {
    ...CtkChichibuhonCommon,
    lineName: '秩父線',
};

const CtkChichibuhon = [
    {
        ekimeiKanj: '羽生',
        ekimeiKana: 'はにゅう',
        ekimeiRoma: 'HANYU',
        sttnAddr: '埼玉県羽生市南一丁目1-62',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '西羽生',
        ekimeiKana: 'にしはにゅう',
        ekimeiRoma: 'NISHI-HANYU',
        sttnAddr: '埼玉県羽生市西五丁目32-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '新郷',
        ekimeiKana: 'しんごう',
        ekimeiRoma: 'SHINGO',
        sttnAddr: '埼玉県羽生市大字上新郷1950-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '武州荒木',
        ekimeiKana: 'ぶしゅうあらき',
        ekimeiRoma: 'BUSHU-ARAKI',
        sttnAddr: '埼玉県行田市大字荒木1411',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '東行田',
        ekimeiKana: 'ひがしぎょうだ',
        ekimeiRoma: 'HIGASHI-GYODA',
        sttnAddr: '埼玉県行田市桜町二丁目23-12',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '行田市',
        ekimeiKana: 'ぎょうだし',
        ekimeiRoma: 'GYODA-SHI',
        sttnAddr: '埼玉県行田市中央19-18',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '持田',
        ekimeiKana: 'もちだ',
        ekimeiRoma: 'MOCHIDA',
        sttnAddr: '埼玉県行田市城西四丁目6-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: 'ソシオ流通センター',
        ekimeiKana: 'ソシオりゅうつうセンター',
        ekimeiRoma: 'SOCIO DISTRIBUTION CENTER',
        sttnAddr: '埼玉県熊谷市戸出102番地1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '熊谷',
        ekimeiKana: 'くまがや',
        ekimeiRoma: 'KUMAGAYA',
        sttnAddr: '埼玉県熊谷市桜木町一丁目202-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '上熊谷',
        ekimeiKana: 'かみくまがや',
        ekimeiRoma: 'KAMI-KUMAGAYA',
        sttnAddr: '埼玉県熊谷市宮本町255-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '石原',
        ekimeiKana: 'いしわら',
        ekimeiRoma: 'ISHIWARA',
        sttnAddr: '埼玉県熊谷市石原1485-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: 'ひろせ野鳥の森',
        ekimeiKana: 'ひろせやちょうのもり',
        ekimeiRoma: 'HIROSE-YACHONOMORI',
        sttnAddr: '埼玉県熊谷市広瀬1040-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '大麻生',
        ekimeiKana: 'おおあそう',
        ekimeiRoma: 'OASO',
        sttnAddr: '埼玉県熊谷市大麻生1921-6',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '明戸',
        ekimeiKana: 'あけと',
        ekimeiRoma: 'AKETO',
        sttnAddr: '埼玉県深谷市瀬山578-8',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '武川',
        ekimeiKana: 'たけかわ',
        ekimeiRoma: 'TAKEKAWA',
        sttnAddr: '埼玉県深谷市田中77-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '永田',
        ekimeiKana: 'ながた',
        ekimeiRoma: 'NAGATA',
        sttnAddr: '埼玉県深谷市永田155-4',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: 'ふかや花園',
        ekimeiKana: 'ふかやはなぞの',
        ekimeiRoma: 'FUKAYA-HANAZONO',
        sttnAddr: '埼玉県深谷市黒田113',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '小前田',
        ekimeiKana: 'おまえだ',
        ekimeiRoma: 'OMAEDA',
        sttnAddr: '埼玉県深谷市小前田1680-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '桜沢',
        ekimeiKana: 'さくらざわ',
        ekimeiRoma: 'SAKURAZAWA',
        sttnAddr: '埼玉県大里郡寄居町大字桜沢1987-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '寄居',
        ekimeiKana: 'よりい',
        ekimeiRoma: 'Yorii',
        sttnAddr: '埼玉県大里郡寄居町大字寄居1071-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '波久礼',
        ekimeiKana: 'はぐれ',
        ekimeiRoma: 'HAGURE',
        sttnAddr: '埼玉県大里郡寄居町大字末野81-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '樋口',
        ekimeiKana: 'ひぐち',
        ekimeiRoma: 'HIGUCHI',
        sttnAddr: '埼玉県秩父郡長瀞町大字野上下郷939-4',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '野上',
        ekimeiKana: 'のがみ',
        ekimeiRoma: 'NOGAMI',
        sttnAddr: '埼玉県秩父郡長瀞町大字本野上281-3',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '長瀞',
        ekimeiKana: 'ながとろ',
        ekimeiRoma: 'NAGATORO',
        sttnAddr: '埼玉県秩父郡長瀞町大字長瀞529-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '上長瀞',
        ekimeiKana: 'かみながとろ',
        ekimeiRoma: 'KAMI-NAGATORO',
        sttnAddr: '埼玉県秩父郡長瀞町大字長瀞1524-1',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '親鼻',
        ekimeiKana: 'おやはな',
        ekimeiRoma: 'OYAHANA',
        sttnAddr: '埼玉県秩父郡皆野町大字皆野2499-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '皆野',
        ekimeiKana: 'みなの',
        ekimeiRoma: 'MINANO',
        sttnAddr: '埼玉県秩父郡皆野町大字皆野971-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '和銅黒谷',
        ekimeiKana: 'わどうくろや',
        ekimeiRoma: 'WADO-KUROYA',
        sttnAddr: '埼玉県秩父市黒谷412-4',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '大野原',
        ekimeiKana: 'おおのはら',
        ekimeiRoma: 'ONOHARA',
        sttnAddr: '埼玉県秩父市大野原306-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '秩父',
        ekimeiKana: 'ちちぶ',
        ekimeiRoma: 'CHICHIBU',
        sttnAddr: '埼玉県秩父市宮側町1-8',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '御花畑',
        ekimeiKana: 'おはなばたけ',
        ekimeiRoma: 'OHANABATAKE',
        sttnAddr: '埼玉県秩父市東町21-3',
        ...CtkChichibuhonCommon,
    },
    {
        ekimeiKanj: '影森',
        ekimeiKana: 'かげもり',
        ekimeiRoma: 'KAGEMORI',
        sttnAddr: '埼玉県秩父市上影森71-4',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '浦山口',
        ekimeiKana: 'うらやまぐち',
        ekimeiRoma: 'URAYAMAGUCHI',
        sttnAddr: '埼玉県秩父市荒川久那字平沢3895',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '武州中川',
        ekimeiKana: 'ぶしゅうなかがわ',
        ekimeiRoma: 'BUSHU-NAKAGAWA',
        sttnAddr: '埼玉県秩父市荒川上田野1451-5',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '武州日野',
        ekimeiKana: 'ぶしゅうひの',
        ekimeiRoma: 'BUSHU-HINO',
        sttnAddr: '埼玉県秩父市荒川日野822-2',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '白久',
        ekimeiKana: 'しろく',
        ekimeiRoma: 'SHIROKU',
        sttnAddr: '	埼玉県秩父市荒川白久字原524-8',
        ...CtkChichibuhonCommon1,
    },
    {
        ekimeiKanj: '三峰口',
        ekimeiKana: 'みつみねぐち',
        ekimeiRoma: 'MITSUMINEGUCHI',
        sttnAddr: '埼玉県秩父市荒川白久1625',
        ...CtkChichibuhonCommon1,
    },
];
