const TokyuIkegamiCommon = {
    ...compNameTokyu,
    lineName: '池上線',
};

const TokyuIkegami = [
    {
        ekimeiKanj: '五反田',
        ekimeiKana: 'ごたんだ',
        ekimeiRoma: 'Gotanda',
        sttnAddr: '東京都品川区東五反田二丁目1番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '大崎広小路',
        ekimeiKana: 'おおさきひろこうじ',
        ekimeiRoma: 'Ōsakihirokōji',
        sttnAddr: '東京都品川区大崎四丁目1番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '戸越銀座',
        ekimeiKana: 'とごしぎんざ',
        ekimeiRoma: 'Togoshi-ginza',
        sttnAddr: '東京都品川区平塚二丁目16番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '荏原中延',
        ekimeiKana: 'えばらなかのぶ',
        ekimeiRoma: 'Ebara-nakanobu',
        sttnAddr: '東京都品川区中延二丁目8番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '旗の台',
        ekimeiKana: 'はたのだい',
        ekimeiRoma: 'Hatanodai',
        sttnAddr: '東京都品川区旗の台二丁目13番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '長原',
        ekimeiKana: 'ながはら',
        ekimeiRoma: 'Nagahara',
        sttnAddr: '東京都大田区上池台一丁目10番10号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '洗足池',
        ekimeiKana: 'せんぞくいけ',
        ekimeiRoma: 'Senzoku-ike',
        sttnAddr: '東京都大田区東雪谷一丁目1番6号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '石川台',
        ekimeiKana: 'いしかわだい',
        ekimeiRoma: 'Ishikawa-dai',
        sttnAddr: '東京都大田区東雪谷二丁目23番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '雪が谷大塚',
        ekimeiKana: 'ゆきがやおおつか',
        ekimeiRoma: 'Yukigaya-ōtsuka',
        sttnAddr: '東京都大田区南雪谷二丁目2番16号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '御嶽山',
        ekimeiKana: 'おんたけさん',
        ekimeiRoma: 'Ontakesan',
        sttnAddr: '東京都大田区北嶺町32番17号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '久が原',
        ekimeiKana: 'くがはら',
        ekimeiRoma: 'Kugahara',
        sttnAddr: '東京都大田区南久が原二丁目6番10号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '千鳥町',
        ekimeiKana: 'ちどりちょう',
        ekimeiRoma: 'Chidorichō',
        sttnAddr: '東京都大田区千鳥一丁目20番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '池上',
        ekimeiKana: 'いけがみ',
        ekimeiRoma: 'Ikegami',
        sttnAddr: '東京都大田区池上六丁目3番10号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '蓮沼',
        ekimeiKana: 'はすぬま',
        ekimeiRoma: 'Hasunuma',
        sttnAddr: '東京都大田区西蒲田七丁目17番1号',
        ...TokyuIkegamiCommon,
    },
    {
        ekimeiKanj: '蒲田',
        ekimeiKana: 'かまた',
        ekimeiRoma: 'Kamata',
        sttnAddr: '東京都大田区西蒲田七丁目69番1号',
        ...TokyuIkegamiCommon,
    },
];
