const TokyuMeguroCommon = {
    ...compNameTokyu,
    lineName: '目黒線',
    lineBack1: '#009cd2',
};

const TokyuMeguro = [
    {
        ekimeiKanj: '目黒',
        ekimeiKana: 'めぐろ',
        ekimeiRoma: 'Meguro',
        sttnAddr: '東京都品川区上大崎四丁目2-1',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '不動前',
        ekimeiKana: 'ふどうまえ',
        ekimeiRoma: 'Fudō-mae',
        sttnAddr: '東京都品川区西五反田五丁目12-1',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '武蔵小山',
        ekimeiKana: 'むさしこやま',
        ekimeiRoma: 'Musashi-koyama',
        sttnAddr: '東京都品川区小山三丁目4-8',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '西小山',
        ekimeiKana: 'にしこやま',
        ekimeiRoma: 'Nishi-koyama',
        sttnAddr: '東京都品川区小山六丁目3-10',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '洗足',
        ekimeiKana: 'せんぞく',
        ekimeiRoma: 'Senzoku',
        sttnAddr: '東京都目黒区洗足二丁目21-1',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '大岡山',
        ekimeiKana: 'おおおかやま',
        ekimeiRoma: 'Ōokayama',
        sttnAddr: '東京都大田区北千束三丁目27番1号',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '奥沢',
        ekimeiKana: 'おくさわ',
        ekimeiRoma: 'Okusawa',
        sttnAddr: '東京都世田谷区奥沢三丁目47番17号',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '田園調布',
        ekimeiKana: 'でんえんちょうふ',
        ekimeiRoma: 'Den-en-chōfu',
        sttnAddr: '東京都大田区田園調布三丁目25-18',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '多摩川',
        ekimeiKana: 'たまがわ',
        ekimeiRoma: 'Tamagawa',
        sttnAddr: '東京都大田区田園調布一丁目53-8',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '新丸子',
        ekimeiKana: 'しんまるこ',
        ekimeiRoma: 'Shin-maruko',
        sttnAddr: '川崎市中原区新丸子町766番地',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '武蔵小杉',
        ekimeiKana: 'むさしこすぎ',
        ekimeiRoma: 'Musashi-kosugi',
        sttnAddr: '川崎市中原区小杉町三丁目472番地',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '元住吉',
        ekimeiKana: 'もとすみよし',
        ekimeiRoma: 'Motosumiyoshi',
        sttnAddr: '川崎市中原区木月一丁目36-1',
        ...TokyuMeguroCommon,
    },
    {
        ekimeiKanj: '日吉',
        ekimeiKana: 'ひよし',
        ekimeiRoma: 'Hiyoshi',
        sttnAddr: '横浜市港北区日吉二丁目1-1',
        ...TokyuMeguroCommon,
    },
];
