const TokyuOoimachiCommon = {
    ...compNameTokyu,
    lineName: '大井町線',
};

const TokyuOoimachi = [
    {
        ekimeiKanj: '大井町',
        ekimeiKana: 'おおいまち',
        ekimeiRoma: 'Ōimachi',
        sttnAddr: '東京都品川区大井一丁目1-1',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '下神明',
        ekimeiKana: 'しもしんめい',
        ekimeiRoma: 'Shimo-shimmei',
        sttnAddr: '東京都品川区西品川一丁目29番6号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '戸越公園',
        ekimeiKana: 'とごしこうえん',
        ekimeiRoma: 'Togoshi-kōen',
        sttnAddr: '東京都品川区戸越五丁目10番15号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '中延',
        ekimeiKana: 'なかのぶ',
        ekimeiRoma: 'Nakanobu',
        sttnAddr: '東京都品川区中延四丁目5-5',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '荏原町',
        ekimeiKana: 'えばらまち',
        ekimeiRoma: 'Ebara-machi',
        sttnAddr: '東京都品川区中延五丁目2-1',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '旗の台',
        ekimeiKana: 'はたのだい',
        ekimeiRoma: 'Hatanodai',
        sttnAddr: '東京都品川区旗の台二丁目13番1号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '北千束',
        ekimeiKana: 'きたせんぞく',
        ekimeiRoma: 'Kita-senzoku',
        sttnAddr: '東京都大田区北千束二丁目16番1号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '大岡山',
        ekimeiKana: 'おおおかやま',
        ekimeiRoma: 'Ōokayama',
        sttnAddr: '東京都大田区北千束三丁目27番1号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '緑が丘',
        ekimeiKana: 'みどりがおか',
        ekimeiRoma: 'Midorigaoka',
        sttnAddr: '東京都目黒区緑が丘三丁目1番12号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '自由が丘',
        ekimeiKana: 'じゆうがおか',
        ekimeiRoma: 'Jiyūgaoka',
        sttnAddr: '東京都目黒区自由が丘一丁目9-8',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '九品仏',
        ekimeiKana: 'くほんぶつ',
        ekimeiRoma: 'Kuhombutsu',
        sttnAddr: '東京都世田谷区奥沢七丁目20-1',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '尾山台',
        ekimeiKana: 'おやまだい',
        ekimeiRoma: 'Oyamadai',
        sttnAddr: '東京都世田谷区等々力五丁目5番7号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '等々力',
        ekimeiKana: 'とどろき',
        ekimeiRoma: 'Todoroki',
        sttnAddr: '東京都世田谷区等々力三丁目1番1号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '上野毛',
        ekimeiKana: 'かみのげ',
        ekimeiRoma: 'Kaminoge',
        sttnAddr: '東京都世田谷区上野毛一丁目26番6号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '二子玉川',
        ekimeiKana: 'ふたこたまがわ',
        ekimeiRoma: 'Futako-tamagawa',
        sttnAddr: '東京都世田谷区玉川二丁目22番13号',
        ...TokyuOoimachiCommon,
    },
    {
        ekimeiKanj: '溝の口',
        ekimeiKana: 'みぞのくち',
        ekimeiRoma: 'Mizonokuchi',
        sttnAddr: '川崎市高津区溝口二丁目1番1号',
        ...TokyuOoimachiCommon,
    },
];
