const TokyuDenentoshiCommon = {
    ...compNameTokyu,
    lineName: '田園都市線',
};

const TokyuDenentoshi = [
    {
        ekimeiKanj: '渋谷',
        ekimeiKana: 'しぶや',
        ekimeiRoma: 'Shibuya',
        sttnAddr: '東京都渋谷区道玄坂二丁目1番1号',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '池尻大橋',
        ekimeiKana: 'いけじりおおはし',
        ekimeiRoma: 'Ikejiri-ōhashi',
        sttnAddr: '東京都世田谷区池尻三丁目2番',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '三軒茶屋',
        ekimeiKana: 'さんげんぢゃや',
        ekimeiRoma: 'Sangen-jaya',
        sttnAddr: '東京都世田谷区太子堂二丁目15番',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '駒沢大学',
        ekimeiKana: 'こまざわだいがく',
        ekimeiRoma: 'Komazawa-daigaku',
        sttnAddr: '東京都世田谷区上馬四丁目3番',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '桜新町',
        ekimeiKana: 'さくらしんまち',
        ekimeiRoma: 'Sakura-shimmachi',
        sttnAddr: '東京都世田谷区桜新町二丁目8番',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '用賀',
        ekimeiKana: 'ようが',
        ekimeiRoma: 'Yōga',
        sttnAddr: '東京都世田谷区用賀二丁目39番',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '二子玉川',
        ekimeiKana: 'ふたこたまがわ',
        ekimeiRoma: 'Futako-tamagawa',
        sttnAddr: '東京都世田谷区玉川二丁目22番13号',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '二子新地',
        ekimeiKana: 'ふたこしんち',
        ekimeiRoma: 'Futako-shinchi',
        sttnAddr: '川崎市高津区二子二丁目2番1号',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '高津',
        ekimeiKana: 'たかつ',
        ekimeiRoma: 'Takatsu',
        sttnAddr: '川崎市高津区二子四丁目1番1号',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '溝の口',
        ekimeiKana: 'みぞのくち',
        ekimeiRoma: 'Mizonokuchi',
        sttnAddr: '川崎市高津区溝口二丁目1番1号',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '梶が谷',
        ekimeiKana: 'かじがや',
        ekimeiRoma: 'Kajigaya',
        sttnAddr: '川崎市高津区末長一丁目48番6号',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '宮崎台',
        ekimeiKana: 'みやざきだい',
        ekimeiRoma: 'Miyazakidai',
        sttnAddr: '川崎市宮前区宮崎二丁目10番地12',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '宮前平',
        ekimeiKana: 'みやまえだいら',
        ekimeiRoma: 'Miyamaedaira',
        sttnAddr: '川崎市宮前区宮前平一丁目11番地1',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '鷺沼',
        ekimeiKana: 'さぎぬま',
        ekimeiRoma: 'Saginuma',
        sttnAddr: '川崎市宮前区鷺沼三丁目1番地1',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: 'たまプラーザ',
        ekimeiKana: 'たまぷらーざ',
        ekimeiRoma: 'Tama-plaza',
        sttnAddr: '横浜市青葉区美しが丘一丁目3番地',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: 'あざみ野',
        ekimeiKana: 'あざみの',
        ekimeiRoma: 'Azamino',
        sttnAddr: '横浜市青葉区あざみ野二丁目1番地1',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '江田',
        ekimeiKana: 'えだ',
        ekimeiRoma: 'Eda',
        sttnAddr: '横浜市青葉区荏田町2360番地',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '市が尾',
        ekimeiKana: 'いちがお',
        ekimeiRoma: 'Ichigao',
        sttnAddr: '横浜市青葉区市ケ尾町1156番地1',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '藤が丘',
        ekimeiKana: 'ふじがおか',
        ekimeiRoma: 'Fujigaoka',
        sttnAddr: '横浜市青葉区藤が丘二丁目5番地4',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '青葉台',
        ekimeiKana: 'あおばだい',
        ekimeiRoma: 'Aobadai',
        sttnAddr: '横浜市青葉区青葉台一丁目7番地3',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '田奈',
        ekimeiKana: 'たな',
        ekimeiRoma: 'Tana',
        sttnAddr: '横浜市青葉区田奈町76番地',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '長津田',
        ekimeiKana: 'ながつた',
        ekimeiRoma: 'Nagatsuta',
        sttnAddr: '横浜市緑区長津田四丁目1-1',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: 'つくし野',
        ekimeiKana: 'つくしの',
        ekimeiRoma: 'Tsukushino',
        sttnAddr: '東京都町田市つくし野四丁目1番地',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: 'すずかけ台',
        ekimeiKana: 'すずかけだい',
        ekimeiRoma: 'Suzukakedai',
        sttnAddr: '東京都町田市南つくし野三丁目1番地',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '南町田グランベリーパーク',
        ekimeiKana: 'みなみまちだぐらんべりーぱーく',
        ekimeiRoma: 'Minami-machida Grandberry Park',
        sttnAddr: '東京都町田市鶴間三丁目3番地2',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: 'つきみ野',
        ekimeiKana: 'つきみの',
        ekimeiRoma: 'Tsukimino',
        sttnAddr: '神奈川県大和市つきみ野五丁目8番地1',
        ...TokyuDenentoshiCommon,
    },
    {
        ekimeiKanj: '中央林間',
        ekimeiKana: 'ちゅうおうりんかん',
        ekimeiRoma: 'Chūō-rinkan',
        sttnAddr: '神奈川県大和市中央林間四丁目6番3号',
        ...TokyuDenentoshiCommon,
    },
];
