const TokyuTouyokoCommon = {
    ...compNameTokyu,
    lineName: '東横線',
};

const TokyuTouyoko = [
    {
        ekimeiKanj: '渋谷',
        ekimeiKana: 'しぶや',
        ekimeiRoma: 'Shibuya',
        sttnAddr: '東京都渋谷区渋谷二丁目21番13号',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '代官山',
        ekimeiKana: 'だいかんやま',
        ekimeiRoma: 'Daikan-yama',
        sttnAddr: '東京都渋谷区代官山町19-4',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '中目黒',
        ekimeiKana: 'なかめぐろ',
        ekimeiRoma: 'Naka-meguro',
        sttnAddr: '東京都目黒区上目黒三丁目4-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '祐天寺',
        ekimeiKana: 'ゆうてんじ',
        ekimeiRoma: 'Yūtenji',
        sttnAddr: '東京都目黒区祐天寺二丁目13-3',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '学芸大学',
        ekimeiKana: 'がくげいだいがく',
        ekimeiRoma: 'Gakugei-daigaku',
        sttnAddr: '東京都目黒区鷹番三丁目2-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '都立大学',
        ekimeiKana: 'とりつだいがく',
        ekimeiRoma: 'Toritsu-daigaku',
        sttnAddr: '東京都目黒区中根一丁目5-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '自由が丘',
        ekimeiKana: 'じゆうがおか',
        ekimeiRoma: 'Jiyūgaoka',
        sttnAddr: '東京都目黒区自由が丘一丁目9-8',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '田園調布',
        ekimeiKana: 'でんえんちょうふ',
        ekimeiRoma: 'Den-en-chōfu',
        sttnAddr: '東京都大田区田園調布三丁目25-18',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '多摩川',
        ekimeiKana: 'たまがわ',
        ekimeiRoma: 'Tamagawa',
        sttnAddr: '東京都大田区田園調布一丁目53-8',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '新丸子',
        ekimeiKana: 'しんまるこ',
        ekimeiRoma: 'Shin-maruko',
        sttnAddr: '川崎市中原区新丸子町766番地',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '武蔵小杉',
        ekimeiKana: 'むさしこすぎ',
        ekimeiRoma: 'Musashi-kosugi',
        sttnAddr: '川崎市中原区小杉町三丁目472番地',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '元住吉',
        ekimeiKana: 'もとすみよし',
        ekimeiRoma: 'Motosumiyoshi',
        sttnAddr: '川崎市中原区木月一丁目36-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '日吉',
        ekimeiKana: 'ひよし',
        ekimeiRoma: 'Hiyoshi',
        sttnAddr: '横浜市港北区日吉二丁目1-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '綱島',
        ekimeiKana: 'つなしま',
        ekimeiRoma: 'Tsunashima',
        sttnAddr: '横浜市港北区綱島西一丁目1-8',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '大倉山',
        ekimeiKana: 'おおくらやま',
        ekimeiRoma: 'Ōkurayama',
        sttnAddr: '横浜市港北区大倉山一丁目1-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '菊名',
        ekimeiKana: 'きくな',
        ekimeiRoma: 'Kikuna',
        sttnAddr: '横浜市港北区菊名七丁目1-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '妙蓮寺',
        ekimeiKana: 'みょうれんじ',
        ekimeiRoma: 'Myōrenji',
        sttnAddr: '横浜市港北区菊名一丁目1-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '白楽',
        ekimeiKana: 'はくらく',
        ekimeiRoma: 'Hakuraku',
        sttnAddr: '横浜市神奈川区白楽100',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '東白楽',
        ekimeiKana: 'ひがしはくらく',
        ekimeiRoma: 'Higashi-hakuraku',
        sttnAddr: '横浜市神奈川区白楽12-1',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '反町',
        ekimeiKana: 'たんまち',
        ekimeiRoma: 'Tammachi',
        sttnAddr: '横浜市神奈川区上反町1丁目1番地',
        ...TokyuTouyokoCommon,
    },
    {
        ekimeiKanj: '横浜',
        ekimeiKana: 'よこはま',
        ekimeiRoma: 'Yokohama',
        sttnAddr: '横浜市西区南幸一丁目1-1',
        ...TokyuTouyokoCommon,
    },
];
