const SeibuIkebukuroCommon = {
    ...compNameSeibu,
    lineName: '池袋線',
    lineBack1: '#ef810f',
};

const SeibuIkebukuro = [
    {
        ekimeiKanj: '池袋',
        ekimeiKana: 'いけぶくろ',
        ekimeiRoma: 'Ikebukuro',
        sttnAddr: '	東京都豊島区南池袋一丁目28-1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '椎名町',
        ekimeiKana: 'しいなまち',
        ekimeiRoma: 'Shiinamachi',
        sttnAddr: '東京都豊島区長崎一丁目1番22号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '東長崎',
        ekimeiKana: 'ひがしながさき',
        ekimeiRoma: 'Higashi-Nagasaki',
        sttnAddr: '東京都豊島区長崎五丁目1-1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '江古田',
        ekimeiKana: 'えこだ',
        ekimeiRoma: 'Ekoda',
        sttnAddr: '東京都練馬区旭丘一丁目78番7号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '桜台',
        ekimeiKana: 'さくらだい',
        ekimeiRoma: 'Sakuradai',
        sttnAddr: '東京都練馬区桜台一丁目5番1号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '練馬',
        ekimeiKana: 'ねりま',
        ekimeiRoma: 'Nerima',
        sttnAddr: '東京都練馬区練馬一丁目3-5',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '中村橋',
        ekimeiKana: 'なかむらばし',
        ekimeiRoma: 'Nakamurabashi',
        sttnAddr: '東京都練馬区中村北四丁目2-1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '富士見台',
        ekimeiKana: 'ふじみだい',
        ekimeiRoma: 'Fujimidai',
        sttnAddr: '東京都練馬区貫井三丁目7番4号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '練馬高野台',
        ekimeiKana: 'ねりまたかのだい',
        ekimeiRoma: 'Nerima-Takanodai',
        sttnAddr: '東京都練馬区高野台一丁目7番27号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '石神井公園',
        ekimeiKana: 'しゃくじいこうえん',
        ekimeiRoma: 'Shakujii-kōen',
        sttnAddr: '東京都練馬区石神井町三丁目23番10号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '大泉学園',
        ekimeiKana: 'おおいずみがくえん',
        ekimeiRoma: 'Ōizumi-gakuen',
        sttnAddr: '東京都練馬区東大泉一丁目29-7',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '保谷',
        ekimeiKana: 'ほうや',
        ekimeiRoma: 'Hōya',
        sttnAddr: '東京都西東京市東町三丁目14番30号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: 'ひばりヶ丘',
        ekimeiKana: 'ひばりがおか',
        ekimeiRoma: 'Hibarigaoka',
        sttnAddr: '東京都西東京市住吉町三丁目9番19号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '東久留米',
        ekimeiKana: 'ひがしくるめ',
        ekimeiRoma: 'Higashi-Kurume',
        sttnAddr: '東京都東久留米市東本町1番8号',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '清瀬',
        ekimeiKana: 'きよせ',
        ekimeiRoma: 'Kiyose',
        sttnAddr: '東京都清瀬市元町一丁目2-4',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '秋津',
        ekimeiKana: 'あきつ',
        ekimeiRoma: 'Akitsu',
        sttnAddr: '東京都東村山市秋津町五丁目7-8',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '所沢',
        ekimeiKana: 'ところざわ',
        ekimeiRoma: 'Tokorozawa',
        sttnAddr: '埼玉県所沢市くすのき台一丁目14-5',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '西所沢',
        ekimeiKana: 'にしところざわ',
        ekimeiRoma: 'Nishi-Tokorozawa',
        sttnAddr: '埼玉県所沢市西所沢一丁目11-9',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '小手指',
        ekimeiKana: 'こてさし',
        ekimeiRoma: 'Kotesashi',
        sttnAddr: '埼玉県所沢市小手指町一丁目8-1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '狭山ヶ丘',
        ekimeiKana: 'さやまがおか',
        ekimeiRoma: 'Sayamagaoka',
        sttnAddr: '埼玉県所沢市狭山ヶ丘一丁目2980',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '武蔵藤沢',
        ekimeiKana: 'むさしふじさわ',
        ekimeiRoma: 'Musashi-Fujisawa',
        sttnAddr: '埼玉県入間市下藤沢494-4',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '稲荷山公園',
        ekimeiKana: 'いなりやまこうえん',
        ekimeiRoma: 'Inariyama-kōen',
        sttnAddr: '埼玉県狭山市稲荷山一丁目1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '入間市',
        ekimeiKana: 'いるまし',
        ekimeiRoma: 'Irumashi',
        sttnAddr: '埼玉県入間市河原町2-1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '仏子',
        ekimeiKana: 'ぶし',
        ekimeiRoma: 'Bushi',
        sttnAddr: '埼玉県入間市仏子880',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '元加治',
        ekimeiKana: 'もとかじ',
        ekimeiRoma: 'Motokaji',
        sttnAddr: '埼玉県入間市野田167',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '飯能',
        ekimeiKana: 'はんのう',
        ekimeiRoma: 'Hannō',
        sttnAddr: '埼玉県飯能市仲町11-21',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '東飯能',
        ekimeiKana: 'ひがしはんのう',
        ekimeiRoma: 'Higashi-Hannō',
        sttnAddr: '埼玉県飯能市東町1-5',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '高麗',
        ekimeiKana: 'こま',
        ekimeiRoma: 'Koma',
        sttnAddr: '埼玉県日高市武蔵台一丁目1-1',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '武蔵横手',
        ekimeiKana: 'むさしよこて',
        ekimeiRoma: 'Musashi-Yokote',
        sttnAddr: '埼玉県日高市横手字山下750',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '東吾野',
        ekimeiKana: 'ひがしあがの',
        ekimeiRoma: 'Higashi-Agano',
        sttnAddr: '埼玉県飯能市平戸220',
        ...SeibuIkebukuroCommon,
    },
    {
        ekimeiKanj: '吾野',
        ekimeiKana: 'あがの',
        ekimeiRoma: 'Agano',
        sttnAddr: '埼玉県飯能市坂石町分326-1',
        ...SeibuIkebukuroCommon,
    },
];
