const SeibuShinjukuCommon = {
    ...compNameSeibu,
    lineName: '新宿線',
    lineBack1: '#00a6bf',
};

const SeibuShinjuku = [
    {
        ekimeiKanj: '西武新宿',
        ekimeiKana: 'せいぶしんじゅく',
        ekimeiRoma: 'Seibu-Shinjuku',
        sttnAddr: '東京都新宿区歌舞伎町一丁目30-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '高田馬場',
        ekimeiKana: 'たかだのばば',
        ekimeiRoma: 'Takadanobaba',
        sttnAddr: '東京都新宿区高田馬場一丁目35-2',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '下落合',
        ekimeiKana: 'しもおちあい',
        ekimeiRoma: 'Shimo-Ochiai',
        sttnAddr: '東京都新宿区下落合一丁目16-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '中井',
        ekimeiKana: 'なかい',
        ekimeiRoma: 'Nakai',
        sttnAddr: '東京都新宿区中井一丁目19-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '新井薬師前',
        ekimeiKana: 'あらいやくしまえ',
        ekimeiRoma: 'Araiyakushi-mae',
        sttnAddr: '東京都中野区上高田五丁目43-20',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '沼袋',
        ekimeiKana: 'ぬまぶくろ',
        ekimeiRoma: 'Numabukuro',
        sttnAddr: '東京都中野区沼袋一丁目35-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '野方',
        ekimeiKana: 'のがた',
        ekimeiRoma: 'Nogata',
        sttnAddr: '東京都中野区野方六丁目3-3',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '都立家政',
        ekimeiKana: 'とりつかせい',
        ekimeiRoma: 'Toritsu-Kasei',
        sttnAddr: '東京都中野区鷺宮一丁目16-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '鷺ノ宮',
        ekimeiKana: 'さぎのみや',
        ekimeiRoma: 'Saginomiya',
        sttnAddr: '東京都中野区鷺宮三丁目15-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '下井草',
        ekimeiKana: 'しもいぐさ',
        ekimeiRoma: 'Shimo-Igusa',
        sttnAddr: '東京都杉並区下井草二丁目44-10',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '井荻',
        ekimeiKana: 'いおぎ',
        ekimeiRoma: 'Iogi',
        sttnAddr: '東京都杉並区下井草五丁目23-15',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '上井草',
        ekimeiKana: 'かみいぐさ',
        ekimeiRoma: 'Kami-Igusa',
        sttnAddr: '東京都杉並区上井草三丁目32-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '上石神井',
        ekimeiKana: 'かみしゃくじい',
        ekimeiRoma: 'Kami-Shakujii',
        sttnAddr: '東京都練馬区上石神井一丁目2-45',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '武蔵関',
        ekimeiKana: 'むさしせき',
        ekimeiRoma: 'Musashi-Seki',
        sttnAddr: '東京都練馬区関町北二丁目29-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '東伏見',
        ekimeiKana: 'ひがしふしみ',
        ekimeiRoma: 'Higashi-Fushimi',
        sttnAddr: '東京都西東京市東伏見二丁目5-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '西武柳沢',
        ekimeiKana: 'せいぶやぎさわ',
        ekimeiRoma: 'Seibu-Yagisawa',
        sttnAddr: '東京都西東京市保谷町3丁目11-24',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '田無',
        ekimeiKana: 'たなし',
        ekimeiRoma: 'Tanashi',
        sttnAddr: '東京都西東京市田無町四丁目1-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '花小金井',
        ekimeiKana: 'はなこがねい',
        ekimeiRoma: 'Hana-Koganei',
        sttnAddr: '東京都小平市花小金井一丁目10-5',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '小平',
        ekimeiKana: 'こだいら',
        ekimeiRoma: 'Kodaira',
        sttnAddr: '東京都小平市美園町一丁目34-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '久米川',
        ekimeiKana: 'くめがわ',
        ekimeiRoma: 'Kumegawa',
        sttnAddr: '東京都東村山市栄町二丁目3-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '東村山',
        ekimeiKana: 'ひがしむらやま',
        ekimeiRoma: 'Higashi-Murayama',
        sttnAddr: '東京都東村山市本町二丁目3番地32',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '所沢',
        ekimeiKana: 'ところざわ',
        ekimeiRoma: 'Tokorozawa',
        sttnAddr: '埼玉県所沢市くすのき台一丁目14-5',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '航空公園',
        ekimeiKana: 'こうくうこうえん',
        ekimeiRoma: 'Kōkū-kōen',
        sttnAddr: '埼玉県所沢市並木二丁目',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '新所沢',
        ekimeiKana: 'しんところざわ',
        ekimeiRoma: 'Shin-Tokorozawa',
        sttnAddr: '埼玉県所沢市緑町一丁目21-25',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '入曽',
        ekimeiKana: 'いりそ',
        ekimeiRoma: 'Iriso',
        sttnAddr: '埼玉県狭山市大字南入曽字堂ノ前原567',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '狭山市',
        ekimeiKana: 'さやまし',
        ekimeiRoma: 'Sayamashi',
        sttnAddr: '埼玉県狭山市入間川一丁目1-1',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '新狭山',
        ekimeiKana: 'しんさやま',
        ekimeiRoma: 'Shin-Sayama',
        sttnAddr: '埼玉県狭山市新狭山三丁目',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '南大塚',
        ekimeiKana: 'みなみおおつか',
        ekimeiRoma: 'Minami-Ōtsuka',
        sttnAddr: '埼玉県川越市南台三丁目14',
        ...SeibuShinjukuCommon,
    },
    {
        ekimeiKanj: '本川越',
        ekimeiKana: 'ほんかわごえ',
        ekimeiRoma: 'Hon-Kawagoe',
        sttnAddr: '埼玉県川越市新富町一丁目22',
        ...SeibuShinjukuCommon,
    },
];
