const JreChuuouhonCommon = {
    ...compNameJre,
    lineName: '中央本線',
    lineName1: { lineName: '中央本線' },
    lineName2: { lineName: '中央東線' },
};

const JreChuuouhon = [
    /*
    {
        ekimeiKanj: '高尾',
        ekimeiKana: 'たかお',
        ekimeiRoma: 'Takao',
        sttnAddr: '東京都八王子市高尾町1201-2',
        ...JreChuuouhonCommon
    },
    */
    {
        ekimeiKanj: '相模湖',
        ekimeiKana: 'さがみこ',
        ekimeiRoma: 'Sagamiko',
        sttnAddr: '神奈川県相模原市緑区与瀬',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '藤野',
        ekimeiKana: 'ふじの',
        ekimeiRoma: 'Fujino',
        sttnAddr: '神奈川県相模原市緑区小渕',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '上野原',
        ekimeiKana: 'うえのはら',
        ekimeiRoma: 'Uenohara',
        sttnAddr: '山梨県上野原市新田',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '四方津',
        ekimeiKana: 'しおつ',
        ekimeiRoma: 'Shiotsu',
        sttnAddr: '山梨県上野原市四方津',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '梁川',
        ekimeiKana: 'やながわ',
        ekimeiRoma: 'Yanagawa',
        sttnAddr: '山梨県大月市梁川町綱の上',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '鳥沢',
        ekimeiKana: 'とりさわ',
        ekimeiRoma: 'Torisawa',
        sttnAddr: '山梨県大月市富浜町鳥沢',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '猿橋',
        ekimeiKana: 'さるはし',
        ekimeiRoma: 'Saruhashi',
        sttnAddr: '山梨県大月市猿橋町殿上',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '大月',
        ekimeiKana: 'おおつき',
        ekimeiRoma: 'Ōtsuki',
        sttnAddr: '山梨県大月市大月一丁目',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '初狩',
        ekimeiKana: 'はつかり',
        ekimeiRoma: 'Hatsukari',
        sttnAddr: '山梨県大月市初狩町下初狩',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '笹子',
        ekimeiKana: 'ささご',
        ekimeiRoma: 'Sasago',
        sttnAddr: '山梨県大月市笹子町黒野田',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '甲斐大和',
        ekimeiKana: 'かいやまと',
        ekimeiRoma: 'Kai-Yamato',
        sttnAddr: '山梨県甲州市大和町初鹿野',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '勝沼ぶどう郷',
        ekimeiKana: 'かつぬまぶどうきょう',
        ekimeiRoma: 'Katsunumabudōkyō',
        sttnAddr: '山梨県甲州市勝沼町菱山',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '塩山',
        ekimeiKana: 'えんざん',
        ekimeiRoma: 'Enzan',
        sttnAddr: '山梨県甲州市塩山上於曽',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '東山梨',
        ekimeiKana: 'ひがしやまなし',
        ekimeiRoma: 'Higashi-Yamanashi',
        sttnAddr: '山梨県山梨市上之割',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '山梨市',
        ekimeiKana: 'やまなしし',
        ekimeiRoma: 'Yamanashishi',
        sttnAddr: '山梨県山梨市上神内川',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '春日居町',
        ekimeiKana: 'かすがいちょう',
        ekimeiRoma: 'Kasugaichō',
        sttnAddr: '山梨県笛吹市春日居町別田',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '石和温泉',
        ekimeiKana: 'いさわおんせん',
        ekimeiRoma: 'Isawa-Onsen',
        sttnAddr: '山梨県笛吹市石和町松本',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '酒折',
        ekimeiKana: 'さかおり',
        ekimeiRoma: 'Sakaori',
        sttnAddr: '山梨県甲府市酒折一丁目',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '甲府',
        ekimeiKana: 'こうふ',
        ekimeiRoma: 'Kōfu',
        sttnAddr: '山梨県甲府市丸の内一丁目',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '竜王',
        ekimeiKana: 'りゅうおう',
        ekimeiRoma: 'Ryūō',
        sttnAddr: '山梨県甲斐市竜王新町',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '塩崎',
        ekimeiKana: 'しおざき',
        ekimeiRoma: 'Shiozaki',
        sttnAddr: '山梨県甲斐市下今井',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '韮崎',
        ekimeiKana: 'にらさき',
        ekimeiRoma: 'Nirasaki',
        sttnAddr: '山梨県韮崎市若宮一丁目',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '新府',
        ekimeiKana: 'しんぷ',
        ekimeiRoma: 'Shimpu',
        sttnAddr: '山梨県韮崎市中田町中條',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '穴山',
        ekimeiKana: 'あなやま',
        ekimeiRoma: 'Anayama',
        sttnAddr: '山梨県韮崎市穴山町',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '日野春',
        ekimeiKana: 'ひのはる',
        ekimeiRoma: 'Hinoharu',
        sttnAddr: '山梨県北杜市長坂町富岡',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '長坂',
        ekimeiKana: 'ながさか',
        ekimeiRoma: 'Nagasaka',
        sttnAddr: '山梨県北杜市長坂町長坂上条',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '小淵沢',
        ekimeiKana: 'こぶちざわ',
        ekimeiRoma: 'Kobuchizawa',
        sttnAddr: '山梨県北杜市小淵沢町',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '信濃境',
        ekimeiKana: 'しなのさかい',
        ekimeiRoma: 'Shinano-Sakai',
        sttnAddr: '長野県諏訪郡富士見町境',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '富士見',
        ekimeiKana: 'ふじみ',
        ekimeiRoma: 'Fujimi',
        sttnAddr: '長野県諏訪郡富士見町富士見',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: 'すずらんの里',
        ekimeiKana: 'すずらんのさと',
        ekimeiRoma: 'Suzurannosato',
        sttnAddr: '長野県諏訪郡富士見町富士見',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '青柳',
        ekimeiKana: 'あおやぎ',
        ekimeiRoma: 'Aoyagi',
        sttnAddr: '長野県茅野市金沢青柳',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '茅野',
        ekimeiKana: 'ちの',
        ekimeiRoma: 'Chino',
        sttnAddr: '長野県茅野市塚原１丁目１',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '上諏訪',
        ekimeiKana: 'かみすわ',
        ekimeiRoma: 'Kami-Suwa',
        sttnAddr: '長野県諏訪市諏訪一丁目',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '下諏訪',
        ekimeiKana: 'しもすわ',
        ekimeiRoma: 'Shimo-Suwa',
        sttnAddr: '長野県諏訪郡下諏訪町広瀬町',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '岡谷',
        ekimeiKana: 'おかや',
        ekimeiRoma: 'Okaya',
        sttnAddr: '長野県岡谷市本町一丁目',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: 'みどり湖',
        ekimeiKana: 'みどりこ',
        ekimeiRoma: 'Midoriko',
        sttnAddr: '長野県塩尻市大字上西条道畑',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '塩尻',
        ekimeiKana: 'しおじり',
        ekimeiRoma: 'Shiojiri',
        sttnAddr: '長野県塩尻市大門八番町',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName2,
    },
    {
        ekimeiKanj: '川岸',
        ekimeiKana: 'かわぎし',
        ekimeiRoma: 'Kawagishi',
        sttnAddr: '長野県岡谷市川岸東',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '辰野',
        ekimeiKana: 'たつの',
        ekimeiRoma: 'Tatsuno',
        sttnAddr: '長野県上伊那郡辰野町大字辰野',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '信濃川島',
        ekimeiKana: 'しなのかわしま',
        ekimeiRoma: 'Shinano-Kawashima',
        sttnAddr: '長野県上伊那郡辰野町大字上島',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
    {
        ekimeiKanj: '小野',
        ekimeiKana: 'おの',
        ekimeiRoma: 'Ono',
        sttnAddr: '長野県上伊那郡辰野町大字小野',
        ...compNameJre,
        ...JreChuuouhonCommon.lineName1,
    },
];
