const JreJoubankankouCommon = {
    ...compNameJre,
    lineName: '常磐緩行線',
    lineName1: { lineName: '常磐線（各駅停車）'},
    passArea: '["NHSP"]',
}

const JreJoubankankou = [
    {
        ekimeiKanj: '綾瀬',
        ekimeiKana: 'あやせ',
        ekimeiRoma: 'Ayase',
        sttnAddr: '東京都足立区綾瀬三丁目1-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '亀有',
        ekimeiKana: 'かめあり',
        ekimeiRoma: 'Kameari',
        sttnAddr: '東京都葛飾区亀有三丁目25-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '金町',
        ekimeiKana: 'かなまち',
        ekimeiRoma: 'Kanamachi',
        sttnAddr: '東京都葛飾区金町六丁目4-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '松戸',
        ekimeiKana: 'まつど',
        ekimeiRoma: 'Matsudo',
        sttnAddr: '千葉県松戸市松戸1181',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '北松戸',
        ekimeiKana: 'きたまつど',
        ekimeiRoma: 'Kita-Matsudo',
        sttnAddr: '千葉県松戸市上本郷905',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '馬橋',
        ekimeiKana: 'まばし',
        ekimeiRoma: 'Mabashi',
        sttnAddr: '千葉県松戸市馬橋121',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '新松戸',
        ekimeiKana: 'しんまつど',
        ekimeiRoma: 'Shim-Matsudo',
        sttnAddr: '千葉県松戸市幸谷571-3',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '北小金',
        ekimeiKana: 'きたこがね',
        ekimeiRoma: 'Kita-Kogane',
        sttnAddr: '千葉県松戸市小金8-3',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '南柏',
        ekimeiKana: 'みなみかしわ',
        ekimeiRoma: 'Minami-Kashiwa',
        sttnAddr: '千葉県柏市南柏一丁目1-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '柏',
        ekimeiKana: 'かしわ',
        ekimeiRoma: 'Kashiwa',
        sttnAddr: '千葉県柏市柏一丁目1-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '北柏',
        ekimeiKana: 'きたかしわ',
        ekimeiRoma: 'Kita-Kashiwa',
        sttnAddr: '千葉県柏市根戸字中馬場1901',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '我孫子',
        ekimeiKana: 'あびこ',
        ekimeiRoma: 'Abiko',
        sttnAddr: '千葉県我孫子市本町二丁目1-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '天王台',
        ekimeiKana: 'てんのうだい',
        ekimeiRoma: 'Tennōdai',
        sttnAddr: '千葉県我孫子市柴崎台一丁目19-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
    {
        ekimeiKanj: '取手',
        ekimeiKana: 'とりで',
        ekimeiRoma: 'Toride',
        sttnAddr: '茨城県取手市中央町1-1',
        ...compNameJre,
        ...JreJoubankankouCommon.lineName1,
        ...JreJoubankankouCommon.passArea,
    },
];
