const JreKururiCommon = {
    ...compNameJre,
    lineName: '久留里線',
}

const JreKururi = [
    {
        ekimeiKanj: '木更津',
        ekimeiKana: 'きさらづ',
        ekimeiRoma: 'Kisarazu',
        sttnAddr: '千葉県木更津市富士見一丁目1-1',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '祇園',
        ekimeiKana: 'ぎおん',
        ekimeiRoma: 'Gion',
        sttnAddr: '千葉県木更津市祇園473',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '上総清川',
        ekimeiKana: 'かずさきよかわ',
        ekimeiRoma: 'Kazusa-Kiyokawa',
        sttnAddr: '千葉県木更津市菅生799',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '東清川',
        ekimeiKana: 'ひがしきよかわ',
        ekimeiRoma: 'Higashi-Kiyokawa',
        sttnAddr: '千葉県木更津市笹子486',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '横田',
        ekimeiKana: 'よこた',
        ekimeiRoma: 'Yokota',
        sttnAddr: '千葉県袖ケ浦市横田2177-2',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '東横田',
        ekimeiKana: 'ひがしよこた',
        ekimeiRoma: 'Higashi-Yokota',
        sttnAddr: '千葉県袖ケ浦市横田442',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '馬来田',
        ekimeiKana: 'まくた',
        ekimeiRoma: 'Makuta',
        sttnAddr: '千葉県木更津市真里107',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '下郡',
        ekimeiKana: 'しもごおり',
        ekimeiRoma: 'Shimogōri',
        sttnAddr: '千葉県君津市山本湯名下2',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '小櫃',
        ekimeiKana: 'おびつ',
        ekimeiRoma: 'Obitsu',
        sttnAddr: '千葉県君津市末吉152',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '俵田',
        ekimeiKana: 'たわらだ',
        ekimeiRoma: 'Tawarada',
        sttnAddr: '千葉県君津市俵田1630',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '久留里',
        ekimeiKana: 'くるり',
        ekimeiRoma: 'Kururi',
        sttnAddr: '千葉県君津市久留里市場198',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '平山',
        ekimeiKana: 'ひらやま',
        ekimeiRoma: 'Hirayama',
        sttnAddr: '千葉県君津市平山759',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '上総松丘',
        ekimeiKana: 'かずさまつおか',
        ekimeiRoma: 'Kazusa-Matsuoka',
        sttnAddr: '千葉県君津市広岡1692',
        ...JreKururiCommon,
    },
    {
        ekimeiKanj: '上総亀山',
        ekimeiKana: 'かずさかめやま',
        ekimeiRoma: 'Kazusa-Kameyama',
        sttnAddr: '千葉県君津市藤林98',
        ...JreKururiCommon,
    },
];
