const JreKoumiCommon = {
    ...compNameJre,
    lineName: '小海線',
};

const JreKoumi = [
    {
        ekimeiKanj: '小淵沢',
        ekimeiKana: 'こぶちざわ',
        ekimeiRoma: 'Kobuchizawa',
        sttnAddr: '山梨県北杜市小淵沢町',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '甲斐小泉',
        ekimeiKana: 'かいこいずみ',
        ekimeiRoma: 'Kai-Koizumi',
        sttnAddr: '山梨県北杜市長坂町小荒間',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '甲斐大泉',
        ekimeiKana: 'かいおおいずみ',
        ekimeiRoma: 'Kai-Ōizumi',
        sttnAddr: '山梨県北杜市大泉町西井出',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '清里',
        ekimeiKana: 'きよさと',
        ekimeiRoma: 'Kiyosato',
        sttnAddr: '山梨県北杜市高根町清里',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '野辺山',
        ekimeiKana: 'のべやま',
        ekimeiRoma: 'Nobeyama',
        sttnAddr: '長野県南佐久郡南牧村大字野辺山306',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '信濃川上',
        ekimeiKana: 'しなのかわかみ',
        ekimeiRoma: 'Shinano-Kawakami',
        sttnAddr: '長野県南佐久郡川上村大字御所平',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '佐久広瀬',
        ekimeiKana: 'さくひろせ',
        ekimeiRoma: 'Saku-Hirose',
        sttnAddr: '長野県南佐久郡南牧村大字広瀬',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '佐久海ノ口',
        ekimeiKana: 'さくうみのくち',
        ekimeiRoma: 'Saku-Uminokuchi',
        sttnAddr: '長野県南佐久郡南牧村大字海ノ口',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '海尻',
        ekimeiKana: 'うみじり',
        ekimeiRoma: 'Umijiri',
        sttnAddr: '長野県南佐久郡南牧村大字海尻',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '松原湖',
        ekimeiKana: 'まつばらこ',
        ekimeiRoma: 'Matsubarako',
        sttnAddr: '長野県南佐久郡小海町大字豊里',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '小海',
        ekimeiKana: 'こうみ',
        ekimeiRoma: 'Koumi',
        sttnAddr: '長野県南佐久郡小海町大字小海',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '馬流',
        ekimeiKana: 'まながし',
        ekimeiRoma: 'Managashi',
        sttnAddr: '長野県南佐久郡小海町大字東馬流',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '高岩',
        ekimeiKana: 'たかいわ',
        ekimeiRoma: 'Takaiwa',
        sttnAddr: '長野県南佐久郡佐久穂町大字穂積',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '八千穂',
        ekimeiKana: 'やちほ',
        ekimeiRoma: 'Yachiho',
        sttnAddr: '長野県南佐久郡佐久穂町大字穂積',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '海瀬',
        ekimeiKana: 'かいぜ',
        ekimeiRoma: 'Kaize',
        sttnAddr: '長野県南佐久郡佐久穂町大字海瀬',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '羽黒下',
        ekimeiKana: 'はぐろした',
        ekimeiRoma: 'Haguroshita',
        sttnAddr: '長野県南佐久郡佐久穂町大字平林',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '青沼',
        ekimeiKana: 'あおぬま',
        ekimeiRoma: 'Aonuma',
        sttnAddr: '長野県佐久市入澤',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '臼田',
        ekimeiKana: 'うすだ',
        ekimeiRoma: 'Usuda',
        sttnAddr: '長野県佐久市下越',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '龍岡城',
        ekimeiKana: 'たつおかじょう',
        ekimeiRoma: 'Tatsuokajō',
        sttnAddr: '	長野県佐久市田口',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '太田部',
        ekimeiKana: 'おおたべ',
        ekimeiRoma: 'Ōtabe',
        sttnAddr: '長野県佐久市太田部',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '中込',
        ekimeiKana: 'なかごみ',
        ekimeiRoma: 'Nakagomi',
        sttnAddr: '長野県佐久市中込',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '滑津',
        ekimeiKana: 'なめづ',
        ekimeiRoma: 'Namezu',
        sttnAddr: '長野県佐久市中込',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '北中込',
        ekimeiKana: 'きたなかごみ',
        ekimeiRoma: 'Kita-Nakagomi',
        sttnAddr: '長野県佐久市中込',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '岩村田',
        ekimeiKana: 'いわむらだ',
        ekimeiRoma: 'Iwamurada',
        sttnAddr: '長野県佐久市岩村田',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '佐久平',
        ekimeiKana: 'さくだいら',
        ekimeiRoma: 'Sakudaira',
        sttnAddr: '長野県佐久市佐久平駅東1-1',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '中佐都',
        ekimeiKana: 'なかさと',
        ekimeiRoma: 'Nakasato',
        sttnAddr: '長野県佐久市長土呂',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '美里',
        ekimeiKana: 'みさと',
        ekimeiRoma: 'Misato',
        sttnAddr: '長野県小諸市大字市字土橋',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '三岡',
        ekimeiKana: 'みつおか',
        ekimeiRoma: 'Mitsuoka',
        sttnAddr: '長野県小諸市大字森山',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '乙女',
        ekimeiKana: 'おとめ',
        ekimeiRoma: 'Otome',
        sttnAddr: '長野県小諸市甲1284',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '東小諸',
        ekimeiKana: 'ひがしこもろ',
        ekimeiRoma: 'Higashi-Komoro',
        sttnAddr: '長野県小諸市甲1550',
        ...JreKoumiCommon,
    },
    {
        ekimeiKanj: '小諸',
        ekimeiKana: 'こもろ',
        ekimeiRoma: 'KOMORO',
        sttnAddr: '長野県小諸市相生町一丁目1-1',
        ...JreKoumiCommon,
    },
];
