const JreUchibouCommon = {
    ...compNameJre,
    lineName: '内房線',
    lineBack1: '#00b2e5',
};

const JreUchibouCommon1 = {
    ...JreUchibouCommon,
    passArea: '["ShuP", "NHSP"]',
};

const JreUchibouCommon2 = {
    ...JreUchibouCommon,
    passArea: '["ShuP"]',
};

const JreUchibou = [
    /*
    {
        ekimeiKanj: '千葉',
        ekimeiKana: 'ちば',
        ekimeiRoma: 'Chiba',
        sttnAddr: '千葉市中央区新千葉一丁目1-1',
        ...JreUchibouCommon,
    },
    {
        ekimeiKanj: '本千葉',
        ekimeiKana: 'ほんちば',
        ekimeiRoma: 'Hon-Chiba',
        sttnAddr: '千葉市中央区長洲一丁目30-1',
        ...JreUchibouCommon,
    },
    */
    {
        ekimeiKanj: '蘇我',
        ekimeiKana: 'そが',
        ekimeiRoma: 'Soga',
        sttnAddr: '千葉市中央区今井二丁目50-2',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '浜野',
        ekimeiKana: 'はまの',
        ekimeiRoma: 'Hamano',
        sttnAddr: '千葉市中央区村田町700',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '八幡宿',
        ekimeiKana: 'やわたじゅく',
        ekimeiRoma: 'Yawatajuku',
        sttnAddr: '千葉県市原市八幡930-3',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '五井',
        ekimeiKana: 'ごい',
        ekimeiRoma: 'Goi',
        sttnAddr: '千葉県市原市五井中央西二丁目1-11',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '姉ケ崎',
        ekimeiKana: 'あねがさき',
        ekimeiRoma: 'Anegasaki',
        sttnAddr: '千葉県市原市姉崎東',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '長浦',
        ekimeiKana: 'ながうら',
        ekimeiRoma: 'Nagaura',
        sttnAddr: '千葉県袖ケ浦市蔵波5',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '袖ケ浦',
        ekimeiKana: 'そでがうら',
        ekimeiRoma: 'Sodegaura',
        sttnAddr: '千葉県袖ケ浦市奈良輪1198',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '巌根',
        ekimeiKana: 'いわね',
        ekimeiRoma: 'Iwane',
        sttnAddr: '千葉県木更津市岩根三丁目5-1',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '木更津',
        ekimeiKana: 'きさらづ',
        ekimeiRoma: 'Kisarazu',
        sttnAddr: '千葉県木更津市富士見一丁目1-1',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '君津',
        ekimeiKana: 'きみつ',
        ekimeiRoma: 'Kimitsu',
        sttnAddr: '千葉県君津市東坂田一丁目1-1',
        ...JreUchibouCommon1,
    },
    {
        ekimeiKanj: '青堀',
        ekimeiKana: 'あおほり',
        ekimeiRoma: 'Aohori',
        sttnAddr: '千葉県富津市大堀1884',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '大貫',
        ekimeiKana: 'おおぬき',
        ekimeiRoma: 'Ōnuki',
        sttnAddr: '千葉県富津市千種新田364-3',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '佐貫町',
        ekimeiKana: 'さぬきまち',
        ekimeiRoma: 'Sanukimachi',
        sttnAddr: '千葉県富津市亀田540-2',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '上総湊',
        ekimeiKana: 'かずさみなと',
        ekimeiRoma: 'Kazusa-Minato',
        sttnAddr: '千葉県富津市湊736',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '竹岡',
        ekimeiKana: 'たけおか',
        ekimeiRoma: 'Takeoka',
        sttnAddr: '千葉県富津市萩生1105',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '浜金谷',
        ekimeiKana: 'はまかなや',
        ekimeiRoma: 'Hama-Kanaya',
        sttnAddr: '千葉県富津市金谷2209',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '保田',
        ekimeiKana: 'ほた',
        ekimeiRoma: 'Hota',
        sttnAddr: '千葉県安房郡鋸南町保田249',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '安房勝山',
        ekimeiKana: 'あわかつやま',
        ekimeiRoma: 'Awa-Katsuyama',
        sttnAddr: '千葉県安房郡鋸南町竜島838',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '岩井',
        ekimeiKana: 'いわい',
        ekimeiRoma: 'Iwai',
        sttnAddr: '千葉県南房総市市部146-2',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '富浦',
        ekimeiKana: 'とみうら',
        ekimeiRoma: 'Tomiura',
        sttnAddr: '千葉県南房総市富浦町原岡451',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '那古船形',
        ekimeiKana: 'なこふなかた',
        ekimeiRoma: 'Nakofunakata',
        sttnAddr: '千葉県館山市船形227',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '館山',
        ekimeiKana: 'たてやま',
        ekimeiRoma: 'Tateyama',
        sttnAddr: '	千葉県館山市北条1887',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '九重',
        ekimeiKana: 'ここのえ',
        ekimeiRoma: 'Kokonoe',
        sttnAddr: '千葉県館山市二子93',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '千倉',
        ekimeiKana: 'ちくら',
        ekimeiRoma: 'Chikura',
        sttnAddr: '千葉県南房総市千倉町瀬戸2079',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '千歳',
        ekimeiKana: 'ちとせ',
        ekimeiRoma: 'Chitose',
        sttnAddr: '千葉県南房総市千倉町白子524',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '南三原',
        ekimeiKana: 'みなみはら',
        ekimeiRoma: 'Minamihara',
        sttnAddr: '千葉県南房総市和田町松田148',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '和田浦',
        ekimeiKana: 'わだうら',
        ekimeiRoma: 'Wadaura',
        sttnAddr: '千葉県南房総市和田町仁我浦178',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '江見',
        ekimeiKana: 'えみ',
        ekimeiRoma: 'Emi',
        sttnAddr: '千葉県鴨川市西江見95-2',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '太海',
        ekimeiKana: 'ふとみ',
        ekimeiRoma: 'Futomi',
        sttnAddr: '千葉県鴨川市太海2035',
        ...JreUchibouCommon2,
    },
    {
        ekimeiKanj: '安房鴨川',
        ekimeiKana: 'あわかもがわ',
        ekimeiRoma: 'Awa-Kamogawa',
        sttnAddr: '千葉県鴨川市横渚952',
        ...JreUchibouCommon2,
    },
];
