const ShinatetsuShinanotetsudouCommon = {
    ...compNameShinatetsu,
    lineName: 'しなの鉄道線',
    lineBack1: '#f0a401',
    passArea: '["ShuP"]',
};

const ShinatetsuShinanotetsudou = [
    {
        ekimeiKanj: '軽井沢',
        ekimeiKana: 'かるいざわ',
        ekimeiRoma: 'KARUIZAWA',
        sttnAddr: '長野県北佐久郡軽井沢町大字軽井沢1178',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '中軽井沢',
        ekimeiKana: 'なかかるいざわ',
        ekimeiRoma: 'NAKA-KARUIZAWA',
        sttnAddr: '長野県北佐久郡軽井沢町大字長倉3091',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '信濃追分',
        ekimeiKana: 'しなのおいわけ',
        ekimeiRoma: 'SHINANO-OIWAKE',
        sttnAddr: '長野県北佐久郡軽井沢町大字追分1092',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '御代田',
        ekimeiKana: 'みよた',
        ekimeiRoma: 'MIYOTA',
        sttnAddr: '長野県北佐久郡御代田町大字御代田2422',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '平原',
        ekimeiKana: 'ひらはら',
        ekimeiRoma: 'HIRAHARA',
        sttnAddr: '長野県小諸市大字平原603',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '小諸',
        ekimeiKana: 'こもろ',
        ekimeiRoma: 'KOMORO',
        sttnAddr: '長野県小諸市相生町一丁目1-1',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '滋野',
        ekimeiKana: 'しげの',
        ekimeiRoma: 'SHIGENO',
        sttnAddr: '長野県東御市滋野乙977',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '田中',
        ekimeiKana: 'たなか',
        ekimeiRoma: 'TANAKA',
        sttnAddr: '長野県東御市田中279',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '大屋',
        ekimeiKana: 'おおや',
        ekimeiRoma: 'ŌYA',
        sttnAddr: '長野県上田市大屋454',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '信濃国分寺',
        ekimeiKana: 'しなのこくぶんじ',
        ekimeiRoma: 'SHINANO-KOKUBUNJI',
        sttnAddr: '	長野県上田市国分1246-5',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '上田',
        ekimeiKana: 'うえだ',
        ekimeiRoma: 'UEDA',
        sttnAddr: '長野県上田市天神一丁目1-1',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '西上田',
        ekimeiKana: 'にしうえだ',
        ekimeiRoma: 'NISHI-UEDA',
        sttnAddr: '長野県上田市下塩尻341-2',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: 'テクノさかき',
        ekimeiKana: 'てくのさかき',
        ekimeiRoma: 'TEKUNO-SAKAKI',
        sttnAddr: '長野県埴科郡坂城町大字南条4910-5',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '坂城',
        ekimeiKana: 'さかき',
        ekimeiRoma: 'SAKAKI',
        sttnAddr: '長野県埴科郡坂城町大字坂城101-1',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '戸倉',
        ekimeiKana: 'とぐら',
        ekimeiRoma: 'TOGURA',
        sttnAddr: '長野県千曲市大字戸倉1445',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '千曲',
        ekimeiKana: 'ちくま',
        ekimeiRoma: 'CHIKUMA',
        sttnAddr: '長野県千曲市大字寂蒔200',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '屋代',
        ekimeiKana: 'やしろ',
        ekimeiRoma: 'YASHIRO',
        sttnAddr: '長野県千曲市大字小島3139',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '屋代高校前',
        ekimeiKana: 'やしろこうこうまえ',
        ekimeiRoma: 'YASHIROKŌKŌ-MAE',
        sttnAddr: '長野県千曲市大字屋代1411-3',
        ...ShinatetsuShinanotetsudouCommon,
    },
    {
        ekimeiKanj: '篠ノ井',
        ekimeiKana: 'しののい',
        ekimeiRoma: 'Shinonoi',
        sttnAddr: '長野県長野市篠ノ井布施高田',
        ...ShinatetsuShinanotetsudouCommon,
    },
];
