const SendaishichikatetsuNanbokuCommon = {
    ...compNameSendaishichikatetsu,
    lineName: '南北線',
    lineBack1: '#317c66',
};

const SendaishichikatetsuNanboku = [
    {
        ekimeiKanj: '泉中央',
        ekimeiKana: 'いずみちゅうおう',
        ekimeiRoma: 'Izumi-chuo',
        sttnAddr: '仙台市泉区泉中央一丁目7-1',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '八乙女',
        ekimeiKana: 'やおとめ',
        ekimeiRoma: 'Yaotome',
        sttnAddr: '仙台市泉区八乙女中央一丁目4-10',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '黒松',
        ekimeiKana: 'くろまつ',
        ekimeiRoma: 'Kuromatsu',
        sttnAddr: '仙台市泉区旭丘堤二丁目22-1',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '旭ヶ丘',
        ekimeiKana: 'あさひがおか',
        ekimeiRoma: 'Asahigaoka',
        sttnAddr: '仙台市青葉区旭ケ丘三丁目25-15先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '台原',
        ekimeiKana: 'だいのはら',
        ekimeiRoma: 'Dainohara',
        sttnAddr: '仙台市青葉区台原森林公園1-1先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '北仙台',
        ekimeiKana: 'きたせんだい',
        ekimeiRoma: 'Kita-Sendai',
        sttnAddr: '仙台市青葉区昭和町6-6先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '北四番丁',
        ekimeiKana: 'きたよばんちょう',
        ekimeiRoma: 'Kita-Yobancho',
        sttnAddr: '仙台市青葉区二日町13-22先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '勾当台公園',
        ekimeiKana: 'こうとうだいこうえん',
        ekimeiRoma: 'Kotodai-koen',
        sttnAddr: '仙台市青葉区本町三丁目9-2先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '広瀬通',
        ekimeiKana: 'ひろせどおり',
        ekimeiRoma: 'Hirose-dori',
        sttnAddr: '仙台市青葉区本町二丁目10-22先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '仙台',
        ekimeiKana: 'せんだい',
        ekimeiRoma: 'Sendai',
        sttnAddr: '仙台市青葉区中央一丁目10-10地先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '五橋',
        ekimeiKana: 'いつつばし',
        ekimeiRoma: 'Itsutsubashi',
        sttnAddr: '仙台市青葉区五橋二丁目1-10先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '愛宕橋',
        ekimeiKana: 'あたごばし',
        ekimeiRoma: 'Atago-bashi',
        sttnAddr: '仙台市若林区土樋一丁目11-10先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '河原町',
        ekimeiKana: 'かわらまち',
        ekimeiRoma: 'Kawaramachi',
        sttnAddr: '仙台市若林区河原町一丁目5-10先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '長町一丁目',
        ekimeiKana: 'ながまちいっちょうめ',
        ekimeiRoma: 'Nagamachi-Itchome',
        sttnAddr: '仙台市太白区長町一丁目2-12先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '長町',
        ekimeiKana: 'ながまち',
        ekimeiRoma: 'Nagamachi',
        sttnAddr: '仙台市太白区長町五丁目1-15先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '長町南',
        ekimeiKana: 'ながまちみなみ',
        ekimeiRoma: 'Nagamachi-minami',
        sttnAddr: '仙台市太白区長町南三丁目1-60先',
        ...SendaishichikatetsuNanbokuCommon,
    },
    {
        ekimeiKanj: '富沢',
        ekimeiKana: 'とみざわ',
        ekimeiRoma: 'Tomizawa',
        sttnAddr: '仙台市太白区富沢四丁目2-22先',
        ...SendaishichikatetsuNanbokuCommon,
    },
];
