const SendaishichikatetsuTouzaiCommon = {
    ...compNameSendaishichikatetsu,
    lineName: '東西線',
    lineBack1: '#00b1dd',
};

const SendaishichikatetsuTouzai = [
    {
        ekimeiKanj: '八木山動物公園',
        ekimeiKana: 'やぎやまどうぶつこうえん',
        ekimeiRoma: 'Yagiyama Zoological Park',
        sttnAddr: '仙台市太白区八木山本町一丁目43地内',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '青葉山',
        ekimeiKana: 'あおばやま',
        ekimeiRoma: 'Aobayama',
        sttnAddr: '仙台市青葉区荒巻字青葉468-1地内',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '川内',
        ekimeiKana: 'かわうち',
        ekimeiRoma: 'Kawauchi',
        sttnAddr: '仙台市青葉区川内42地内',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '国際センター',
        ekimeiKana: 'こくさいせんたー',
        ekimeiRoma: 'International Center',
        sttnAddr: '仙台市青葉区青葉山2-1外',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '大町西公園',
        ekimeiKana: 'おおまちにしこうえん',
        ekimeiRoma: 'Omachi Nishi-koen',
        sttnAddr: '仙台市青葉区大町二丁目3-14地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '青葉通一番町',
        ekimeiKana: 'あおばどおりいちばんちょう',
        ekimeiRoma: 'Aoba-dori Ichibancho',
        sttnAddr: '仙台市青葉区一番町三丁目3-2地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '仙台',
        ekimeiKana: 'せんだい',
        ekimeiRoma: 'Sendai',
        sttnAddr: '仙台市青葉区中央三丁目6-5地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '宮城野通',
        ekimeiKana: 'みやぎのどおり',
        ekimeiRoma: 'Miyagino-dori',
        sttnAddr: '仙台市宮城野区榴岡四丁目6-1地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '連坊',
        ekimeiKana: 'れんぼう',
        ekimeiRoma: 'Rembo',
        sttnAddr: '仙台市若林区連坊二丁目319-5地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '薬師堂',
        ekimeiKana: 'やくしどう',
        ekimeiRoma: 'Yakushido',
        sttnAddr: '仙台市若林区白萩町401-2地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '卸町',
        ekimeiKana: 'おろしまち',
        ekimeiRoma: 'Oroshimachi',
        sttnAddr: '仙台市若林区卸町一丁目1-7地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '六丁の目',
        ekimeiKana: 'ろくちょうのめ',
        ekimeiRoma: 'Rokuchonome',
        sttnAddr: '仙台市若林区六丁の目中町1-26地先',
        ...SendaishichikatetsuTouzaiCommon,
    },
    {
        ekimeiKanj: '荒井',
        ekimeiKana: 'あらい',
        ekimeiRoma: 'Arai',
        sttnAddr: '仙台市若林区荒井字沓形85-1地内',
        ...SendaishichikatetsuTouzaiCommon,
    },
];
