const OerEnoshimaCommon = {
    ...compNameOer,
    lineName: '江ノ島線',
    lineBack1: '#2288cc',
};

const OerEnoshima = [
    {
        ekimeiKanj: '相模大野',
        ekimeiKana: 'さがみおおの',
        ekimeiRoma: 'Sagami-Ono',
        sttnAddr: '相模原市南区相模大野三丁目8番1号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '東林間',
        ekimeiKana: 'ひがしりんかん',
        ekimeiRoma: 'Higashi-Rinkan',
        sttnAddr: '相模原市南区上鶴間七丁目7番1号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '中央林間',
        ekimeiKana: 'ちゅうおうりんかん',
        ekimeiRoma: 'Chuo-Rinkan',
        sttnAddr: '神奈川県大和市中央林間三丁目3番8号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '南林間',
        ekimeiKana: 'みなみりんかん',
        ekimeiRoma: 'Minami-Rinkan',
        sttnAddr: '神奈川県大和市南林間一丁目6番11号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '鶴間',
        ekimeiKana: 'つるま',
        ekimeiRoma: 'Tsuruma',
        sttnAddr: '神奈川県大和市西鶴間一丁目1番1号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '大和',
        ekimeiKana: 'やまと',
        ekimeiRoma: 'Yamato',
        sttnAddr: '神奈川県大和市大和南一丁目1番1号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '桜ヶ丘',
        ekimeiKana: 'さくらがおか',
        ekimeiRoma: 'Sakuragaoka',
        sttnAddr: '神奈川県大和市福田5522番地',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '高座渋谷',
        ekimeiKana: 'こうざしぶや',
        ekimeiRoma: 'Koza-Shibuya',
        sttnAddr: '	神奈川県大和市渋谷六丁目16番地2',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '長後',
        ekimeiKana: 'ちょうご',
        ekimeiRoma: 'Chogo',
        sttnAddr: '神奈川県藤沢市下土棚472番地',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '湘南台',
        ekimeiKana: 'しょうなんだい',
        ekimeiRoma: 'Shonandai',
        sttnAddr: '神奈川県藤沢市湘南台2丁目15番地',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '六会日大前',
        ekimeiKana: 'むつあいにちだいまえ',
        ekimeiRoma: 'Mutsuai-Nichidai-mae',
        sttnAddr: '神奈川県藤沢市亀井野一丁目1番地1',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '善行',
        ekimeiKana: 'ぜんぎょう',
        ekimeiRoma: 'Zengyo',
        sttnAddr: '神奈川県藤沢市善行一丁目27番地',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '藤沢本町',
        ekimeiKana: 'ふじさわほんまち',
        ekimeiRoma: 'Fujisawa-hommachi',
        sttnAddr: '神奈川県藤沢市藤沢三丁目3番4号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '藤沢',
        ekimeiKana: 'ふじさわ',
        ekimeiRoma: 'Fujisawa',
        sttnAddr: '神奈川県藤沢市南藤沢1番1号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '本鵠沼',
        ekimeiKana: 'ほんくげぬま',
        ekimeiRoma: 'Hon-Kugenuma',
        sttnAddr: '神奈川県藤沢市本鵠沼二丁目13番14号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '鵠沼海岸',
        ekimeiKana: 'くげぬまかいがん',
        ekimeiRoma: 'Kugenuma-kaigan',
        sttnAddr: '神奈川県藤沢市鵠沼海岸二丁目4番10号',
        ...OerEnoshimaCommon,
    },
    {
        ekimeiKanj: '片瀬江ノ島',
        ekimeiKana: 'かたせえのしま',
        ekimeiRoma: 'Katase-Enoshima',
        sttnAddr: '神奈川県藤沢市片瀬海岸二丁目15番3号',
        ...OerEnoshimaCommon,
    },
];
