const TobuNikkouCommon = {
    ...compNameTobu,
    lineName: '日光線',
    lineBack1: 'orange',
};

const TobuNikkou = [
    {
        ekimeiKanj: '東武動物公園',
        ekimeiKana: 'とうぶどうぶつこうえん',
        ekimeiRoma: 'Tobu-dobutsu-koen',
        sttnAddr: '埼玉県南埼玉郡宮代町百間二丁目3-24',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '杉戸高野台',
        ekimeiKana: 'すぎとたかのだい',
        ekimeiRoma: 'Sugito-takanodai',
        sttnAddr: '埼玉県北葛飾郡杉戸町高野台東一丁目19-8',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '幸手',
        ekimeiKana: 'さって',
        ekimeiRoma: 'Satte',
        sttnAddr: '埼玉県幸手市中一丁目1番23号',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '南栗橋',
        ekimeiKana: 'みなみくりはし',
        ekimeiRoma: 'Minami-kurihashi',
        sttnAddr: '埼玉県久喜市南栗橋一丁目20',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '栗橋',
        ekimeiKana: 'くりはし',
        ekimeiRoma: 'Kurihashi',
        sttnAddr: '埼玉県久喜市伊坂中央一丁目18',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '新古河',
        ekimeiKana: 'しんこが',
        ekimeiRoma: 'Shin-koga',
        sttnAddr: '埼玉県加須市向古河732',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '柳生',
        ekimeiKana: 'やぎゅう',
        ekimeiRoma: 'Yagyu',
        sttnAddr: '埼玉県加須市小野袋1834-4',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '板倉東洋大前',
        ekimeiKana: 'いたくらとうようだいまえ',
        ekimeiRoma: 'Itakura-toyodaimae',
        sttnAddr: '群馬県邑楽郡板倉町朝日野一丁目1-1',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '藤岡',
        ekimeiKana: 'ふじおか',
        ekimeiRoma: 'Fujioka',
        sttnAddr: '栃木県栃木市藤岡町藤岡5078-2',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '静和',
        ekimeiKana: 'しずわ',
        ekimeiRoma: 'Shizuwa',
        sttnAddr: '栃木県栃木市岩舟町静和2143',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '新大平下',
        ekimeiKana: 'しんおおひらした',
        ekimeiRoma: 'Shin-ohirashita',
        sttnAddr: '栃木県栃木市大平町富田571-2',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '栃木',
        ekimeiKana: 'とちぎ',
        ekimeiRoma: 'Tochigi',
        sttnAddr: '栃木県栃木市沼和田町1-35',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '新栃木',
        ekimeiKana: 'しんとちぎ',
        ekimeiRoma: 'Shin-tochigi',
        sttnAddr: '栃木県栃木市平柳町一丁目8-18',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '合戦場',
        ekimeiKana: 'かっせんば',
        ekimeiRoma: 'Kassemba',
        sttnAddr: '栃木県栃木市都賀町合戦場513',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '家中',
        ekimeiKana: 'いえなか',
        ekimeiRoma: 'Ienaka',
        sttnAddr: '栃木県栃木市都賀町家中5897-9',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '東武金崎',
        ekimeiKana: 'とうぶかなさき',
        ekimeiRoma: 'Tobu-kanasaki',
        sttnAddr: '栃木県栃木市西方町金崎243-2',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '楡木',
        ekimeiKana: 'にれぎ',
        ekimeiRoma: 'Niregi',
        sttnAddr: '栃木県鹿沼市楡木町1018',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '樅山',
        ekimeiKana: 'もみやま',
        ekimeiRoma: 'Momiyama',
        sttnAddr: '栃木県鹿沼市樅山町702-2',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '新鹿沼',
        ekimeiKana: 'しんかぬま',
        ekimeiRoma: 'Shin-kanuma',
        sttnAddr: '栃木県鹿沼市鳥居跡町1475',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '北鹿沼',
        ekimeiKana: 'きたかぬま',
        ekimeiRoma: 'Kita-kanuma',
        sttnAddr: '栃木県鹿沼市玉田町724',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '板荷',
        ekimeiKana: 'いたが',
        ekimeiRoma: 'Itaga',
        sttnAddr: '栃木県鹿沼市板荷222',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '下小代',
        ekimeiKana: 'しもごしろ',
        ekimeiRoma: 'Shimo-goshiro',
        sttnAddr: '栃木県日光市小代329',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '明神',
        ekimeiKana: 'みょうじん',
        ekimeiRoma: 'Myojin',
        sttnAddr: '栃木県日光市明神883',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '下今市',
        ekimeiKana: 'しもいまいち',
        ekimeiRoma: 'Shimo-imaichi',
        sttnAddr: '栃木県日光市今市1110',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '上今市',
        ekimeiKana: 'かみいまいち',
        ekimeiRoma: 'Kami-imaichi',
        sttnAddr: '栃木県日光市今市533-3',
        ...TobuNikkouCommon,
    },
    {
        ekimeiKanj: '東武日光',
        ekimeiKana: 'とうぶにっこう',
        ekimeiRoma: 'Tobu-nikko',
        sttnAddr: '栃木県日光市松原町4-3',
        ...TobuNikkouCommon,
    },
];
