const TobuToujouhonCommon = {
    ...compNameTobu,
    lineName: '東上本線',
};

const TobuToujouhonCommon1 = {
    ...compNameTobu,
    lineName: '東上線',
};

const TobuToujouhon = [
    {
        ekimeiKanj: '池袋',
        ekimeiKana: 'いけぶくろ',
        ekimeiRoma: 'Ikebukuro',
        sttnAddr: '東京都豊島区西池袋一丁目1-21',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '北池袋',
        ekimeiKana: 'きたいけぶくろ',
        ekimeiRoma: 'Kita-ikebukuro',
        sttnAddr: '東京都豊島区池袋本町一丁目36-6',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '下板橋',
        ekimeiKana: 'しもいたばし',
        ekimeiRoma: 'Shimo-itabashi',
        sttnAddr: '東京都豊島区池袋本町四丁目43-11',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '大山',
        ekimeiKana: 'おおやま',
        ekimeiRoma: 'Oyama',
        sttnAddr: '東京都板橋区大山町4-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '中板橋',
        ekimeiKana: 'なかいたばし',
        ekimeiRoma: 'Naka-itabashi',
        sttnAddr: '東京都板橋区弥生町33-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: 'ときわ台',
        ekimeiKana: 'ときわだい',
        ekimeiRoma: 'Tokiwadai',
        sttnAddr: '東京都板橋区常盤台一丁目43-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '上板橋',
        ekimeiKana: 'かみいたばし',
        ekimeiRoma: 'Kami-itabashi',
        sttnAddr: '東京都板橋区上板橋二丁目36-7',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '東武練馬',
        ekimeiKana: 'とうぶねりま',
        ekimeiRoma: 'Tobu-nerima',
        sttnAddr: '東京都板橋区徳丸二丁目2-14',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '下赤塚',
        ekimeiKana: 'しもあかつか',
        ekimeiRoma: 'Shimo-akatsuka',
        sttnAddr: '東京都板橋区赤塚新町一丁目23-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '成増',
        ekimeiKana: 'なります',
        ekimeiRoma: 'Narimasu',
        sttnAddr: '東京都板橋区成増二丁目13-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '和光市',
        ekimeiKana: 'わこうし',
        ekimeiRoma: 'Wakoshi',
        sttnAddr: '埼玉県和光市本町4-6',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '朝霞',
        ekimeiKana: 'あさか',
        ekimeiRoma: 'Asaka',
        sttnAddr: '埼玉県朝霞市本町二丁目13番52号',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '朝霞台',
        ekimeiKana: 'あさかだい',
        ekimeiRoma: 'Asakadai',
        sttnAddr: '埼玉県朝霞市東弁財一丁目4-17',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '志木',
        ekimeiKana: 'しき',
        ekimeiRoma: 'Shiki',
        sttnAddr: '埼玉県新座市東北二丁目38-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '柳瀬川',
        ekimeiKana: 'やなせがわ',
        ekimeiRoma: 'Yanasegawa',
        sttnAddr: '埼玉県志木市館二丁目5-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: 'みずほ台',
        ekimeiKana: 'みずほだい',
        ekimeiRoma: 'Mizuhodai',
        sttnAddr: '埼玉県富士見市東みずほ台二丁目29-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '鶴瀬',
        ekimeiKana: 'つるせ',
        ekimeiRoma: 'Tsuruse',
        sttnAddr: '埼玉県富士見市鶴瀬東一丁目11-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: 'ふじみ野',
        ekimeiKana: 'ふじみの',
        ekimeiRoma: 'Fujimino',
        sttnAddr: '埼玉県富士見市ふじみ野東一丁目26-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '上福岡',
        ekimeiKana: 'かみふくおか',
        ekimeiRoma: 'Kami-fukuoka',
        sttnAddr: '埼玉県ふじみ野市上福岡一丁目1-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '新河岸',
        ekimeiKana: 'しんがし',
        ekimeiRoma: 'Shingashi',
        sttnAddr: '埼玉県川越市大字砂914-5',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '川越',
        ekimeiKana: 'かわごえ',
        ekimeiRoma: 'Kawagoe',
        sttnAddr: '埼玉県川越市脇田町24-9',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '川越市',
        ekimeiKana: 'かわごえし',
        ekimeiRoma: 'Kawagoeshi',
        sttnAddr: '埼玉県川越市六軒町一丁目4-4',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '霞ヶ関',
        ekimeiKana: 'かすみがせき',
        ekimeiRoma: 'Kasumigaseki',
        sttnAddr: '埼玉県川越市霞ケ関東一丁目1-4',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '鶴ヶ島',
        ekimeiKana: 'つるがしま',
        ekimeiRoma: 'Tsurugashima',
        sttnAddr: '埼玉県鶴ヶ島市大字上広谷18-5',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '若葉',
        ekimeiKana: 'わかば',
        ekimeiRoma: 'Wakaba',
        sttnAddr: '埼玉県坂戸市関間四丁目13-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '坂戸',
        ekimeiKana: 'さかど',
        ekimeiRoma: 'Sakado',
        sttnAddr: '埼玉県坂戸市日の出町1-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '北坂戸',
        ekimeiKana: 'きたさかど',
        ekimeiRoma: 'Kita-sakado',
        sttnAddr: '埼玉県坂戸市末広町1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '高坂',
        ekimeiKana: 'たかさか',
        ekimeiRoma: 'Takasaka',
        sttnAddr: '埼玉県東松山市大字高坂1333-2',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '東松山',
        ekimeiKana: 'ひがしまつやま',
        ekimeiRoma: 'Higashi-matsuyama',
        sttnAddr: '埼玉県東松山市箭弓町一丁目12-11',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '森林公園',
        ekimeiKana: 'しんりんこうえん',
        ekimeiRoma: 'Shinrin-koen',
        sttnAddr: '埼玉県比企郡滑川町大字羽尾3977-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: 'つきのわ',
        ekimeiKana: 'つきのわ',
        ekimeiRoma: 'Tsukinowa',
        sttnAddr: '埼玉県比企郡滑川町月の輪一丁目1-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '武蔵嵐山',
        ekimeiKana: 'むさしらんざん',
        ekimeiRoma: 'Musashi-ranzan',
        sttnAddr: '埼玉県比企郡嵐山町大字菅谷135-6',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '小川町',
        ekimeiKana: 'おがわまち',
        ekimeiRoma: 'Ogawamachi',
        sttnAddr: '埼玉県比企郡小川町大字大塚1146',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '東武竹沢',
        ekimeiKana: 'とうぶたけざわ',
        ekimeiRoma: 'Tobu-takezawa',
        sttnAddr: '埼玉県比企郡小川町大字靱負680-4',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: 'みなみ寄居〈ホンダ寄居前〉',
        ekimeiKana: 'みなみよりい〈ほんだよりいまえ〉',
        ekimeiRoma: 'Minami-yorii〈Honda Yorii-mae〉',
        sttnAddr: '埼玉県大里郡寄居町大字富田字橋ノ入南谷997-14',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '男衾',
        ekimeiKana: 'おぶすま',
        ekimeiRoma: 'Obusuma',
        sttnAddr: '埼玉県大里郡寄居町大字富田1739-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '鉢形',
        ekimeiKana: 'はちがた',
        ekimeiRoma: 'Hachigata',
        sttnAddr: '埼玉県大里郡寄居町大字鉢形16-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '玉淀',
        ekimeiKana: 'たまよど',
        ekimeiRoma: 'Tamayodo',
        sttnAddr: '埼玉県大里郡寄居町大字寄居824-1',
        ...TobuToujouhonCommon1,
    },
    {
        ekimeiKanj: '寄居',
        ekimeiKana: 'よりい',
        ekimeiRoma: 'Yorii',
        sttnAddr: '埼玉県大里郡寄居町大字寄居1071-2',
        ...TobuToujouhonCommon1,
    },
];
