const TobuIsesakiCommon = {
    ...compNameTobu,
    lineName: '伊勢崎線',
};

const TobuIsesakiCommon1 = {
    ...compNameTobu,
    lineName: '東武スカイツリーライン',
    lineBack1: '#0067c0',
    /*lineBack1: 'orange',*/
    /*lineBack2: '#0067c0',*/
};

const TobuIsesakiCommon2 = {
    ...compNameTobu,
    lineName: '東武スカイツリーライン／伊勢崎線',
    lineBack1: '#0067c0',
    lineBack2: '#ed1a3d',
};

const TobuIsesakiCommon3 = {
    ...TobuIsesakiCommon,
    lineBack1: '#ed1a3d',
    /*lineBack2: '#000000',*/
}

const TobuIsesaki = [
    {
        ekimeiKanj: '浅草',
        ekimeiKana: 'あさくさ',
        ekimeiRoma: 'Asakusa',
        sttnAddr: '東京都台東区花川戸一丁目4-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: 'とうきょうスカイツリー',
        ekimeiKana: 'とうきょうスカイツリー',
        ekimeiRoma: 'TOKYO SKYTREE',
        sttnAddr: '東京都墨田区押上一丁目',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '押上〈スカイツリー前〉',
        ekimeiKana: 'おしあげ〈すかいつりーまえ〉',
        ekimeiRoma: 'Oshiage‘SKYTREE’',
        sttnAddr: '東京都墨田区押上一丁目1-65',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '曳舟',
        ekimeiKana: 'ひきふね',
        ekimeiRoma: 'Hikifune',
        sttnAddr: '東京都墨田区東向島2-26-6',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '東向島',
        ekimeiKana: 'ひがしむこうじま',
        ekimeiRoma: 'Higashi-mukojima',
        sttnAddr: '東京都墨田区東向島4-29-7',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '鐘ヶ淵',
        ekimeiKana: 'かねがふち',
        ekimeiRoma: 'Kanegafuchi',
        sttnAddr: '東京都墨田区墨田5-50-2',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '堀切',
        ekimeiKana: 'ほりきり',
        ekimeiRoma: 'Horikiri',
        sttnAddr: '	東京都足立区千住曙町34-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '牛田',
        ekimeiKana: 'うしだ',
        ekimeiRoma: 'Ushida',
        sttnAddr: '東京都足立区千住曙町1-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '北千住',
        ekimeiKana: 'きたせんじゅ',
        ekimeiRoma: 'Kita-senju',
        sttnAddr: '東京都足立区千住旭町42-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '小菅',
        ekimeiKana: 'こすげ',
        ekimeiRoma: 'Kosuge',
        sttnAddr: '東京都足立区足立二丁目46番11号',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '五反野',
        ekimeiKana: 'ごたんの',
        ekimeiRoma: 'Gotanno',
        sttnAddr: '東京都足立区足立三丁目34番6号',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '梅島',
        ekimeiKana: 'うめじま',
        ekimeiRoma: 'Umejima',
        sttnAddr: '東京都足立区梅田七丁目37-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '西新井',
        ekimeiKana: 'にしあらい',
        ekimeiRoma: 'Nishiarai',
        sttnAddr: '東京都足立区西新井栄町二丁目1-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '竹ノ塚',
        ekimeiKana: 'たけのつか',
        ekimeiRoma: 'Takenotsuka',
        sttnAddr: '東京都足立区竹の塚六丁目6番1号',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '谷塚',
        ekimeiKana: 'やつか',
        ekimeiRoma: 'Yatsuka',
        sttnAddr: '埼玉県草加市谷塚一丁目1-22',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '草加',
        ekimeiKana: 'そうか',
        ekimeiRoma: 'Soka',
        sttnAddr: '埼玉県草加市高砂二丁目5-25',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '獨協大学前〈草加松原〉',
        ekimeiKana: 'どっきょうだいがくまえ〈そうかまつばら〉',
        ekimeiRoma: 'Dokkyodaigakumae ‘Soka-Matsubara’',
        sttnAddr: '埼玉県草加市松原一丁目1-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '新田',
        ekimeiKana: 'しんでん',
        ekimeiRoma: 'Shinden',
        sttnAddr: '埼玉県草加市金明町道下263-2',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '蒲生',
        ekimeiKana: 'がもう',
        ekimeiRoma: 'Gamo',
        sttnAddr: '埼玉県越谷市蒲生寿町16-17',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '新越谷',
        ekimeiKana: 'しんこしがや',
        ekimeiRoma: 'Shin-koshigaya',
        sttnAddr: '埼玉県越谷市南越谷一丁目11-4',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '越谷',
        ekimeiKana: 'こしがや',
        ekimeiRoma: 'Koshigaya',
        sttnAddr: '埼玉県越谷市弥生町4-11',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '北越谷',
        ekimeiKana: 'きたこしがや',
        ekimeiRoma: 'Kita-koshigaya',
        sttnAddr: '埼玉県越谷市大沢三丁目4-23',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '大袋',
        ekimeiKana: 'おおぶくろ',
        ekimeiRoma: 'Obukuro',
        sttnAddr: '埼玉県越谷市大字袋山1200',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: 'せんげん台',
        ekimeiKana: 'せんげんだい',
        ekimeiRoma: 'Sengendai',
        sttnAddr: '埼玉県越谷市千間台東一丁目62-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '武里',
        ekimeiKana: 'たけさと',
        ekimeiRoma: 'Takesato',
        sttnAddr: '埼玉県春日部市大場450',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '一ノ割',
        ekimeiKana: 'いちのわり',
        ekimeiRoma: 'Ichinowari',
        sttnAddr: '埼玉県春日部市一ノ割一丁目1-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '春日部',
        ekimeiKana: 'かすかべ',
        ekimeiRoma: 'Kasukabe',
        sttnAddr: '埼玉県春日部市粕壁一丁目10-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '北春日部',
        ekimeiKana: 'きたかすかべ',
        ekimeiRoma: 'Kita-kasukabe',
        sttnAddr: '埼玉県春日部市梅田本町一丁目13-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '姫宮',
        ekimeiKana: 'ひめみや',
        ekimeiRoma: 'Himemiya',
        sttnAddr: '埼玉県南埼玉郡宮代町川端一丁目1-1',
        ...TobuIsesakiCommon1,
    },
    {
        ekimeiKanj: '東武動物公園',
        ekimeiKana: 'とうぶどうぶつこうえん',
        ekimeiRoma: 'Tobu-dobutsu-koen',
        sttnAddr: '埼玉県南埼玉郡宮代町百間二丁目3-24',
        ...TobuIsesakiCommon2,
    },
    {
        ekimeiKanj: '和戸',
        ekimeiKana: 'わど',
        ekimeiRoma: 'Wado',
        sttnAddr: '埼玉県南埼玉郡宮代町和戸一丁目1-1',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '久喜',
        ekimeiKana: 'くき',
        ekimeiRoma: 'Kuki',
        sttnAddr: '埼玉県久喜市久喜中央二丁目1-1',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '鷲宮',
        ekimeiKana: 'わしのみや',
        ekimeiRoma: 'Washinomiya',
        sttnAddr: '埼玉県久喜市鷲宮中央一丁目1-17',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '花崎',
        ekimeiKana: 'はなさき',
        ekimeiRoma: 'Hanasaki',
        sttnAddr: '埼玉県加須市花崎157',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '加須',
        ekimeiKana: 'かぞ',
        ekimeiRoma: 'Kazo',
        sttnAddr: '埼玉県加須市中央一丁目1-15',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '南羽生',
        ekimeiKana: 'みなみはにゅう',
        ekimeiRoma: 'Minami-hanyu',
        sttnAddr: '埼玉県羽生市南羽生一丁目37',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '羽生',
        ekimeiKana: 'はにゅう',
        ekimeiRoma: 'Hanyu',
        sttnAddr: '埼玉県羽生市南一丁目1-62',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '川俣',
        ekimeiKana: 'かわまた',
        ekimeiRoma: 'Kawamata',
        sttnAddr: '群馬県邑楽郡明和町中谷328-3',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '茂林寺前',
        ekimeiKana: 'もりんじまえ',
        ekimeiRoma: 'Morinjimae',
        sttnAddr: '群馬県館林市堀工町1624',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '館林',
        ekimeiKana: 'たてばやし',
        ekimeiRoma: 'Tatebayashi',
        sttnAddr: '群馬県館林市本町2-1-1',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '多々良',
        ekimeiKana: 'たたら',
        ekimeiRoma: 'Tatara',
        sttnAddr: '群馬県館林市日向町987',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '県',
        ekimeiKana: 'あがた',
        ekimeiRoma: 'Agata',
        sttnAddr: '栃木県足利市県町49-1',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '福居',
        ekimeiKana: 'ふくい',
        ekimeiRoma: 'Fukui',
        sttnAddr: '栃木県足利市福居町1157-1',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '東武和泉',
        ekimeiKana: 'とうぶいずみ',
        ekimeiRoma: 'Tobu-izumi',
        sttnAddr: '栃木県足利市福居町2149',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '足利市',
        ekimeiKana: 'あしかがし',
        ekimeiRoma: 'Ashikagashi',
        sttnAddr: '栃木県足利市南町3694',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '野州山辺',
        ekimeiKana: 'やしゅうやまべ',
        ekimeiRoma: 'Yashu-yamabe',
        sttnAddr: '栃木県足利市八幡町637',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '韮川',
        ekimeiKana: 'にらがわ',
        ekimeiRoma: 'Niragawa',
        sttnAddr: '群馬県太田市台之郷町1098-2',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '太田',
        ekimeiKana: 'おおた',
        ekimeiRoma: 'Ota',
        sttnAddr: '群馬県太田市東本町15',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '細谷',
        ekimeiKana: 'ほそや',
        ekimeiRoma: 'Hosoya',
        sttnAddr: '群馬県太田市細谷町1169-4',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '木崎',
        ekimeiKana: 'きざき',
        ekimeiRoma: 'Kizaki',
        sttnAddr: '群馬県太田市新田木崎町45',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '世良田',
        ekimeiKana: 'せらだ',
        ekimeiRoma: 'Serada',
        sttnAddr: '群馬県太田市世良田町2415-1',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '境町',
        ekimeiKana: 'さかいまち',
        ekimeiRoma: 'Sakaimachi',
        sttnAddr: '群馬県伊勢崎市境百々432',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '剛志',
        ekimeiKana: 'ごうし',
        ekimeiRoma: 'Goshi',
        sttnAddr: '群馬県伊勢崎市境保泉1164-4',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '新伊勢崎',
        ekimeiKana: 'しんいせさき',
        ekimeiRoma: 'Shin-isesaki',
        sttnAddr: '群馬県伊勢崎市中央町15-3',
        ...TobuIsesakiCommon3,
    },
    {
        ekimeiKanj: '伊勢崎',
        ekimeiKana: 'いせさき',
        ekimeiRoma: 'Isesaki',
        sttnAddr: '群馬県伊勢崎市曲輪町3-1',
        ...TobuIsesakiCommon3,
    },
];
