const TobuUtsunomiyaCommon = {
    ...compNameTobu,
    lineName: '宇都宮線',
    lineBack1: 'orange',
};

const TobuUtsunomiya = [
    {
        ekimeiKanj: '新栃木',
        ekimeiKana: 'しんとちぎ',
        ekimeiRoma: 'Shin-tochigi',
        sttnAddr: '栃木県栃木市平柳町一丁目8-18',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '野州平川',
        ekimeiKana: 'やしゅうひらかわ',
        ekimeiRoma: 'Yashu-hirakawa',
        sttnAddr: '栃木県栃木市大宮町229-19',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '野州大塚',
        ekimeiKana: 'やしゅうおおつか',
        ekimeiRoma: 'Yashu-otsuka',
        sttnAddr: '栃木県栃木市大塚町1258-10',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '壬生',
        ekimeiKana: 'みぶ',
        ekimeiRoma: 'Mibu',
        sttnAddr: '栃木県下都賀郡壬生町駅東町3-1',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '国谷',
        ekimeiKana: 'くにや',
        ekimeiRoma: 'Kuniya',
        sttnAddr: '栃木県下都賀郡壬生町大字壬生甲3780-8',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: 'おもちゃのまち',
        ekimeiKana: 'おもちゃのまち',
        ekimeiRoma: 'Omochanomachi',
        sttnAddr: '栃木県下都賀郡壬生町幸町一丁目22-1',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '安塚',
        ekimeiKana: 'やすづか',
        ekimeiRoma: 'Yasuzuka',
        sttnAddr: '栃木県下都賀郡壬生町大字安塚1053',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '西川田',
        ekimeiKana: 'にしかわだ',
        ekimeiRoma: 'Nishikawada',
        sttnAddr: '栃木県宇都宮市西川田五丁目1-17',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '江曽島',
        ekimeiKana: 'えそじま',
        ekimeiRoma: 'Esojima',
        sttnAddr: '栃木県宇都宮市大和二丁目12-31',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '南宇都宮',
        ekimeiKana: 'みなみうつのみや',
        ekimeiRoma: 'Minami-utsunomiya',
        sttnAddr: '栃木県宇都宮市吉野二丁目8-23',
        ...TobuUtsunomiyaCommon,
    },
    {
        ekimeiKanj: '東武宇都宮',
        ekimeiKana: 'とうぶうつのみや',
        ekimeiRoma: 'Tobu-utsunomiya',
        sttnAddr: '栃木県宇都宮市宮園町5-4',
        ...TobuUtsunomiyaCommon,
    },
];
