const TobuNodaCommon = {
    ...compNameTobu,
    lineName: '野田線',
};

const TobuNodaCommon1 = {
    ...compNameTobu,
    lineName: '東武アーバンパークライン',
};

const TobuNoda = [
    {
        ekimeiKanj: '大宮',
        ekimeiKana: 'おおみや',
        ekimeiRoma: 'Omiya',
        sttnAddr: 'さいたま市大宮区錦町630',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '北大宮',
        ekimeiKana: 'きたおおみや',
        ekimeiRoma: 'Kita-omiya',
        sttnAddr: 'さいたま市大宮区土手町三丁目285番地',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '大宮公園',
        ekimeiKana: 'おおみやこうえん',
        ekimeiRoma: 'Omiya-koen',
        sttnAddr: 'さいたま市大宮区寿能町一丁目172-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '大和田',
        ekimeiKana: 'おおわだ',
        ekimeiRoma: 'Owada',
        sttnAddr: 'さいたま市見沼区大和田町二丁目1774',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '七里',
        ekimeiKana: 'ななさと',
        ekimeiRoma: 'Nanasato',
        sttnAddr: 'さいたま市見沼区大字風渡野603',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '岩槻',
        ekimeiKana: 'いわつき',
        ekimeiRoma: 'Iwatsuki',
        sttnAddr: 'さいたま市岩槻区本町一丁目1-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '東岩槻',
        ekimeiKana: 'ひがしいわつき',
        ekimeiRoma: 'Higashi-iwatsuki',
        sttnAddr: 'さいたま市岩槻区東岩槻一丁目12-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '豊春',
        ekimeiKana: 'とよはる',
        ekimeiRoma: 'Toyoharu',
        sttnAddr: '埼玉県春日部市上蛭田136-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '八木崎',
        ekimeiKana: 'やぎさき',
        ekimeiRoma: 'Yagisaki',
        sttnAddr: '埼玉県春日部市粕壁6946',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '春日部',
        ekimeiKana: 'かすかべ',
        ekimeiRoma: 'Kasukabe',
        sttnAddr: '埼玉県春日部市粕壁一丁目10-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '藤の牛島',
        ekimeiKana: 'ふじのうしじま',
        ekimeiRoma: 'Fujino-ushijima',
        sttnAddr: '埼玉県春日部市牛島1576',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '南桜井',
        ekimeiKana: 'みなみさくらい',
        ekimeiRoma: 'Minami-sakurai',
        sttnAddr: '埼玉県春日部市米島1185',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '川間',
        ekimeiKana: 'かわま',
        ekimeiRoma: 'Kawama',
        sttnAddr: '千葉県野田市尾崎832',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '七光台',
        ekimeiKana: 'ななこうだい',
        ekimeiRoma: 'Nanakodai',
        sttnAddr: '千葉県野田市光葉町一丁目52番地1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '清水公園',
        ekimeiKana: 'しみずこうえん',
        ekimeiRoma: 'Shimizu-koen',
        sttnAddr: '千葉県野田市清水公園東一丁目32-2',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '愛宕',
        ekimeiKana: 'あたご',
        ekimeiRoma: 'Atago',
        sttnAddr: '千葉県野田市中野台1217',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '野田市',
        ekimeiKana: 'のだし',
        ekimeiRoma: 'Nodashi',
        sttnAddr: '千葉県野田市野田128',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '梅郷',
        ekimeiKana: 'うめさと',
        ekimeiRoma: 'Umesato',
        sttnAddr: '千葉県野田市山崎1892',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '運河',
        ekimeiKana: 'うんが',
        ekimeiRoma: 'Unga',
        sttnAddr: '千葉県流山市東深井字赤土405番地',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '江戸川台',
        ekimeiKana: 'えどがわだい',
        ekimeiRoma: 'Edogawadai',
        sttnAddr: '千葉県流山市江戸川台東一丁目3番地',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '初石',
        ekimeiKana: 'はついし',
        ekimeiRoma: 'Hatsuishi',
        sttnAddr: '千葉県流山市西初石三丁目100番地',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '流山おおたかの森',
        ekimeiKana: 'ながれやまおおたかのもり',
        ekimeiRoma: 'Nagareyama-otakanomori',
        sttnAddr: '千葉県流山市おおたかの森東一丁目1番地1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '豊四季',
        ekimeiKana: 'とよしき',
        ekimeiRoma: 'Toyoshiki',
        sttnAddr: '千葉県柏市豊四季159',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '柏',
        ekimeiKana: 'かしわ',
        ekimeiRoma: 'Kashiwa',
        sttnAddr: '千葉県柏市末広町1-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '新柏',
        ekimeiKana: 'しんかしわ',
        ekimeiRoma: 'Shin-kashiwa',
        sttnAddr: '千葉県柏市新柏一丁目1510',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '増尾',
        ekimeiKana: 'ますお',
        ekimeiRoma: 'Masuo',
        sttnAddr: '千葉県柏市増尾一丁目1-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '逆井',
        ekimeiKana: 'さかさい',
        ekimeiRoma: 'Sakasai',
        sttnAddr: '千葉県柏市逆井848',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '高柳',
        ekimeiKana: 'たかやなぎ',
        ekimeiRoma: 'Takayanagi',
        sttnAddr: '千葉県柏市高柳1489',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '六実',
        ekimeiKana: 'むつみ',
        ekimeiRoma: 'Mutsumi',
        sttnAddr: '千葉県松戸市六実四丁目6-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '新鎌ケ谷',
        ekimeiKana: 'しんかまがや',
        ekimeiRoma: 'Shin-kamagaya',
        sttnAddr: '千葉県鎌ケ谷市新鎌ケ谷二丁目10-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '鎌ヶ谷',
        ekimeiKana: 'かまがや',
        ekimeiRoma: 'Kamagaya',
        sttnAddr: '千葉県鎌ケ谷市道野辺中央二丁目1-10',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '馬込沢',
        ekimeiKana: 'まごめざわ',
        ekimeiRoma: 'Magomezawa',
        sttnAddr: '千葉県船橋市藤原七丁目2番1号',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '塚田',
        ekimeiKana: 'つかだ',
        ekimeiRoma: 'Tsukada',
        sttnAddr: '千葉県船橋市前貝塚町564',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '新船橋',
        ekimeiKana: 'しんふなばし',
        ekimeiRoma: 'Shin-funabashi',
        sttnAddr: '千葉県船橋市山手一丁目3-1',
        ...TobuNodaCommon1,
    },
    {
        ekimeiKanj: '船橋',
        ekimeiKana: 'ふなばし',
        ekimeiRoma: 'Funabashi',
        sttnAddr: '千葉県船橋市本町七丁目1-1',
        ...TobuNodaCommon,
    },
];
