const JomoJomoCommon = {
    ...compNameJomo,
    lineName: '上毛線',
    lineBack1: 'turquoise',
};

const JomoJomo = [
    {
        ekimeiKanj: '中央前橋',
        ekimeiKana: 'ちゅうおうまえばし',
        ekimeiRoma: 'Chūō-Maebashi',
        sttnAddr: '群馬県前橋市城東町三丁目1-1',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '城東',
        ekimeiKana: 'じょうとう',
        ekimeiRoma: 'Jōtō',
        sttnAddr: '群馬県前橋市城東町四丁目23-1',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '三俣',
        ekimeiKana: 'みつまた',
        ekimeiRoma: 'Mitsumata',
        sttnAddr: '群馬県前橋市三俣町一丁目32-5',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '片貝',
        ekimeiKana: 'かたかい',
        ekimeiRoma: 'Katakai',
        sttnAddr: '群馬県前橋市西片貝町一丁目280-5',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '上泉',
        ekimeiKana: 'かみいずみ',
        ekimeiRoma: 'Kamiizumi',
        sttnAddr: '群馬県前橋市上泉町281',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '赤坂',
        ekimeiKana: 'あかさか',
        ekimeiRoma: 'Akasaka',
        sttnAddr: '群馬県前橋市上泉町3444-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '心臓血管センター',
        ekimeiKana: 'しんぞうけっかんセンター',
        ekimeiRoma: 'Shinzō-kekkan Center',
        sttnAddr: '群馬県前橋市亀泉町6-2',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '江木',
        ekimeiKana: 'えぎ',
        ekimeiRoma: 'Egi',
        sttnAddr: '群馬県前橋市江木町1223-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '大胡',
        ekimeiKana: 'おおご',
        ekimeiRoma: 'Ōgo',
        sttnAddr: '群馬県前橋市茂木町41-2',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '樋越',
        ekimeiKana: 'ひごし',
        ekimeiRoma: 'Higoshi',
        sttnAddr: '群馬県前橋市樋越町191-4',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '北原',
        ekimeiKana: 'きたはら',
        ekimeiRoma: 'Kitahara',
        sttnAddr: '群馬県前橋市粕川町込皆戸38-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '新屋',
        ekimeiKana: 'あらや',
        ekimeiRoma: 'Araya',
        sttnAddr: '群馬県前橋市粕川町新屋233-2',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '粕川',
        ekimeiKana: 'かすかわ',
        ekimeiRoma: 'Kasukawa',
        sttnAddr: '群馬県前橋市粕川町西田面293-2',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '膳',
        ekimeiKana: 'ぜん',
        ekimeiRoma: 'Zen',
        sttnAddr: '群馬県前橋市粕川町膳568-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '新里',
        ekimeiKana: 'にいさと',
        ekimeiRoma: 'Niisato',
        sttnAddr: '群馬県桐生市新里町小林126-1',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '新川',
        ekimeiKana: 'にっかわ',
        ekimeiRoma: 'Nikkawa',
        sttnAddr: '群馬県桐生市新里町新川2042-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '東新川',
        ekimeiKana: 'ひがしにっかわ',
        ekimeiRoma: 'Higashi-Nikkawa',
        sttnAddr: '群馬県桐生市新里町新川3906',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '赤城',
        ekimeiKana: 'あかぎ',
        ekimeiRoma: 'Akagi',
        sttnAddr: '群馬県みどり市大間々町大間々2445-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '桐生球場前',
        ekimeiKana: 'きりゅうきゅうじょうまえ',
        ekimeiRoma: 'Kiryū-kyūjō-mae',
        sttnAddr: '群馬県桐生市相生町二丁目532-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '天王宿',
        ekimeiKana: 'てんのうじゅく',
        ekimeiRoma: 'Tennōjuku',
        sttnAddr: '群馬県桐生市相生町二丁目477-3',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '富士山下',
        ekimeiKana: 'ふじやました',
        ekimeiRoma: 'Fujiyama-shita',
        sttnAddr: '群馬県桐生市相生町二丁目274-7',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '丸山下',
        ekimeiKana: 'まるやました',
        ekimeiRoma: 'Maruyama-shita',
        sttnAddr: '	群馬県桐生市堤町三丁目9-1',
        ...JomoJomoCommon,
    },
    {
        ekimeiKanj: '西桐生',
        ekimeiKana: 'にしきりゅう',
        ekimeiRoma: 'Nishi-Kiryū',
        sttnAddr: '群馬県桐生市宮前町二丁目1-33',
        ...JomoJomoCommon,
    },
];
