const JrcChuuouhonCommon = {
    ...compNameJrc,
    lineName: '中央本線',
    lineBack1: '#3b6c9c',
};

const JrcChuuouhonCommon1 = {
    ...JrcChuuouhonCommon,
    lineName: '中央西線',
}

const JrcChuuouhon = [
    {
        ekimeiKanj: '塩尻',
        ekimeiKana: 'しおじり',
        ekimeiRoma: 'Shiojiri',
        sttnAddr: '長野県塩尻市大門八番町',
        ...JrcChuuouhonCommon1,
    },
    {
        ekimeiKanj: '洗馬',
        ekimeiKana: 'せば',
        ekimeiRoma: 'Seba',
        sttnAddr: '長野県塩尻市大字宗賀洗馬',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '日出塩',
        ekimeiKana: 'ひでしお',
        ekimeiRoma: 'Hideshio',
        sttnAddr: '長野県塩尻市大字宗賀日出塩',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '贄川',
        ekimeiKana: 'にえかわ',
        ekimeiRoma: 'Niekawa',
        sttnAddr: '長野県塩尻市大字贄川',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '木曽平沢',
        ekimeiKana: 'きそひらさわ',
        ekimeiRoma: 'Kiso-hirasawa',
        sttnAddr: '長野県塩尻市大字木曽平沢',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '奈良井',
        ekimeiKana: 'ならい',
        ekimeiRoma: 'Narai',
        sttnAddr: '長野県塩尻市大字奈良井',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '藪原',
        ekimeiKana: 'やぶはら',
        ekimeiRoma: 'Yabuhara',
        sttnAddr: '長野県木曽郡木祖村大字薮原',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '宮ノ越',
        ekimeiKana: 'みやのこし',
        ekimeiRoma: 'Miyanokoshi',
        sttnAddr: '長野県木曽郡木曽町日義宮ノ越',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '原野',
        ekimeiKana: 'はらの',
        ekimeiRoma: 'Harano',
        sttnAddr: '長野県木曽郡木曽町日義原野',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '木曽福島',
        ekimeiKana: 'きそふくしま',
        ekimeiRoma: 'Kiso-Fukushima',
        sttnAddr: '長野県木曽郡木曽町福島',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '上松',
        ekimeiKana: 'あげまつ',
        ekimeiRoma: 'Agematsu',
        sttnAddr: '長野県木曽郡上松町駅前通り',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '倉本',
        ekimeiKana: 'くらもと',
        ekimeiRoma: 'Kuramoto',
        sttnAddr: '長野県木曽郡上松町大字荻原',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '須原',
        ekimeiKana: 'すはら',
        ekimeiRoma: 'Suhara',
        sttnAddr: '長野県木曽郡大桑村大字須原',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '大桑',
        ekimeiKana: 'おおくわ',
        ekimeiRoma: 'Ōkuwa',
        sttnAddr: '長野県木曽郡大桑村大字長野',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '野尻',
        ekimeiKana: 'のじり',
        ekimeiRoma: 'Nojiri',
        sttnAddr: '長野県木曽郡大桑村大字野尻',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '十二兼',
        ekimeiKana: 'じゅうにかね',
        ekimeiRoma: 'Jūnikane',
        sttnAddr: '長野県木曽郡南木曽町読書',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '南木曽',
        ekimeiKana: 'なぎそ',
        ekimeiRoma: 'Nagiso',
        sttnAddr: '長野県木曽郡南木曽町読書',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '田立',
        ekimeiKana: 'ただち',
        ekimeiRoma: 'Tadachi',
        sttnAddr: '長野県木曽郡南木曽町田立',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '坂下',
        ekimeiKana: 'さかした',
        ekimeiRoma: 'Sakashita',
        sttnAddr: '岐阜県中津川市坂下',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '落合川',
        ekimeiKana: 'おちあいがわ',
        ekimeiRoma: 'Ochiaigawa',
        sttnAddr: '岐阜県中津川市落合',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '中津川',
        ekimeiKana: 'なかつがわ',
        ekimeiRoma: 'Nakatsugawa',
        sttnAddr: '岐阜県中津川市太田町',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '美乃坂本',
        ekimeiKana: 'みのさかもと',
        ekimeiRoma: 'Mino-Sakamoto',
        sttnAddr: '岐阜県中津川市千旦林坂本',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '恵那',
        ekimeiKana: 'えな',
        ekimeiRoma: 'Ena',
        sttnAddr: '岐阜県恵那市大井町296-2',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '武並',
        ekimeiKana: 'たけなみ',
        ekimeiRoma: 'Takenami',
        sttnAddr: '岐阜県恵那市武並町竹折',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '釜戸',
        ekimeiKana: 'かまど',
        ekimeiRoma: 'Kamado',
        sttnAddr: '岐阜県瑞浪市釜戸町東大島',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '瑞浪',
        ekimeiKana: 'みずなみ',
        ekimeiRoma: 'Mizunami',
        sttnAddr: '岐阜県瑞浪市寺河戸町1171-2',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '土岐市',
        ekimeiKana: 'ときし',
        ekimeiRoma: 'Tokishi',
        sttnAddr: '岐阜県土岐市泉町久尻572-3',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '多治見',
        ekimeiKana: 'たじみ',
        ekimeiRoma: 'Tajimi',
        sttnAddr: '岐阜県多治見市音羽町二丁目',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '古虎渓',
        ekimeiKana: 'ここけい',
        ekimeiRoma: 'Kokokei',
        sttnAddr: '岐阜県多治見市諏訪町神田',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '定光寺',
        ekimeiKana: 'じょうこうじ',
        ekimeiRoma: 'Jōkōji',
        sttnAddr: '愛知県春日井市玉野町',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '高蔵寺',
        ekimeiKana: 'こうぞうじ',
        ekimeiRoma: 'Kōzōji',
        sttnAddr: '愛知県春日井市高蔵寺町三丁目654-1',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '神領',
        ekimeiKana: 'じんりょう',
        ekimeiRoma: 'Jinryō',
        sttnAddr: '愛知県春日井市神領町571',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '春日井',
        ekimeiKana: 'かすがい',
        ekimeiRoma: 'Kasugai',
        sttnAddr: '愛知県春日井市上条町一丁目5162',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '勝川',
        ekimeiKana: 'かちがわ',
        ekimeiRoma: 'Kachigawa',
        sttnAddr: '愛知県春日井市松新町六丁目1',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '新守山',
        ekimeiKana: 'しんもりやま',
        ekimeiRoma: 'Shin-Moriyama',
        sttnAddr: '名古屋市守山区新守町268',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '大曽根',
        ekimeiKana: 'おおぞね',
        ekimeiRoma: 'Ōzone',
        sttnAddr: '名古屋市東区東大曽根町46-6',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '千種',
        ekimeiKana: 'ちくさ',
        ekimeiRoma: 'Chikusa',
        sttnAddr: '名古屋市千種区内山三丁目24-8',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '鶴舞',
        ekimeiKana: 'つるまい',
        ekimeiRoma: 'Tsurumai',
        sttnAddr: '名古屋市中区千代田五丁目23-24',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '金山',
        ekimeiKana: 'かなやま',
        ekimeiRoma: 'Kanayama',
        sttnAddr: '名古屋市中区金山一丁目17-18',
        ...JrcChuuouhonCommon,
    },
    {
        ekimeiKanj: '名古屋',
        ekimeiKana: 'なごや',
        ekimeiRoma: 'Nagoya',
        sttnAddr: '名古屋市中村区名駅一丁目1-4',
        ...JrcChuuouhonCommon,
    },
];
