const JrcKiseihonCommon = {
    ...compNameJrc,
    lineName: '紀勢本線',
    lineBack1: '#f77321',
};

const JrcKiseihon = [
    {
        ekimeiKanj: '亀山',
        ekimeiKana: 'かめやま',
        ekimeiRoma: 'Kameyama',
        sttnAddr: '三重県亀山市御幸町198',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '下庄',
        ekimeiKana: 'しものしょう',
        ekimeiRoma: 'Shimonoshō',
        sttnAddr: '三重県亀山市下庄町578',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '一身田',
        ekimeiKana: 'いしんでん',
        ekimeiRoma: 'Ishinden',
        sttnAddr: '三重県津市大里窪田町861',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '津',
        ekimeiKana: 'つ',
        ekimeiRoma: 'Tsu',
        sttnAddr: '三重県津市羽所町1191-1',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '阿漕',
        ekimeiKana: 'あこぎ',
        ekimeiRoma: 'Akogi',
        sttnAddr: '三重県津市大倉12-24',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '高茶屋',
        ekimeiKana: 'たかちゃや',
        ekimeiRoma: 'Takachaya',
        sttnAddr: '三重県津市高茶屋一丁目6-14',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '六軒',
        ekimeiKana: 'ろっけん',
        ekimeiRoma: 'Rokken',
        sttnAddr: '三重県松阪市小津町',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '松阪',
        ekimeiKana: 'まつさか',
        ekimeiRoma: 'Matsusaka',
        sttnAddr: '三重県松阪市京町301',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '徳和',
        ekimeiKana: 'とくわ',
        ekimeiRoma: 'Tokuwa',
        sttnAddr: '三重県松阪市下村町1855',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '多気',
        ekimeiKana: 'たき',
        ekimeiRoma: 'Taki',
        sttnAddr: '三重県多気郡多気町多気76-1',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '相可',
        ekimeiKana: 'おうか',
        ekimeiRoma: 'Ōka',
        sttnAddr: '三重県多気郡多気町相可1146',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '佐奈',
        ekimeiKana: 'さな',
        ekimeiRoma: 'Sana',
        sttnAddr: '三重県多気郡多気町平谷986',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '栃原',
        ekimeiKana: 'とちはら',
        ekimeiRoma: 'Tochihara',
        sttnAddr: '三重県多気郡大台町栃原1247',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '栃原',
        ekimeiKana: 'とちはら',
        ekimeiRoma: 'Tochihara',
        sttnAddr: '三重県多気郡大台町栃原1247',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '川添',
        ekimeiKana: 'かわぞえ',
        ekimeiRoma: 'Kawazoe',
        sttnAddr: '三重県多気郡大台町上楠281',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '三瀬谷',
        ekimeiKana: 'みせだに',
        ekimeiRoma: 'Misedani',
        sttnAddr: '三重県多気郡大台町佐原654',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '滝原',
        ekimeiKana: 'たきはら',
        ekimeiRoma: 'Takihara',
        sttnAddr: '三重県多気郡大台町大ヶ所155',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '阿曽',
        ekimeiKana: 'あそ',
        ekimeiRoma: 'Aso',
        sttnAddr: '三重県度会郡大紀町阿曽1652',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '伊勢柏崎',
        ekimeiKana: 'いせかしわざき',
        ekimeiRoma: 'Ise-kashiwazaki',
        sttnAddr: '三重県度会郡大紀町崎225',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '大内山',
        ekimeiKana: 'おおうちやま',
        ekimeiRoma: 'Ōuchiyama',
        sttnAddr: '三重県度会郡大紀町大内山759',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '梅ケ谷',
        ekimeiKana: 'うめがだに',
        ekimeiRoma: 'Umegadani',
        sttnAddr: '三重県度会郡大紀町大内山1135',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '紀伊長島',
        ekimeiKana: 'きいながしま',
        ekimeiRoma: 'Kii-Nagashima',
        sttnAddr: '三重県北牟婁郡紀北町東長島301',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '三野瀬',
        ekimeiKana: 'みのせ',
        ekimeiRoma: 'Minose',
        sttnAddr: '三重県北牟婁郡紀北町三浦182',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '船津',
        ekimeiKana: 'ふなつ',
        ekimeiRoma: 'Funatsu',
        sttnAddr: '三重県北牟婁郡紀北町上里456',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '相賀',
        ekimeiKana: 'あいが',
        ekimeiRoma: 'Aiga',
        sttnAddr: '三重県北牟婁郡紀北町相賀239',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '尾鷲',
        ekimeiKana: 'おわせ',
        ekimeiRoma: 'Owase',
        sttnAddr: '三重県尾鷲市中村町7-60',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '大曽根浦',
        ekimeiKana: 'おおそねうら',
        ekimeiRoma: 'Ōsoneura',
        sttnAddr: '三重県尾鷲市大字大曽根浦127',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '九鬼',
        ekimeiKana: 'くき',
        ekimeiRoma: 'Kuki',
        sttnAddr: '三重県尾鷲市九鬼町914',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '三木里',
        ekimeiKana: 'みきさと',
        ekimeiRoma: 'Mikisato',
        sttnAddr: '三重県尾鷲市三木里町1074',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '賀田',
        ekimeiKana: 'かた',
        ekimeiRoma: 'Kata',
        sttnAddr: '三重県尾鷲市曽根町840',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '二木島',
        ekimeiKana: 'にぎしま',
        ekimeiRoma: 'Nigishima',
        sttnAddr: '三重県熊野市二木島町540',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '新鹿',
        ekimeiKana: 'あたしか',
        ekimeiRoma: 'Atashika',
        sttnAddr: '	三重県熊野市新鹿町364',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '波田須',
        ekimeiKana: 'はだす',
        ekimeiRoma: 'Hadasu',
        sttnAddr: '三重県熊野市波田須町713',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '大泊',
        ekimeiKana: 'おおどまり',
        ekimeiRoma: 'Ōdomari',
        sttnAddr: '三重県熊野市大泊町153',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '熊野市',
        ekimeiKana: 'くまのし',
        ekimeiRoma: 'Kumanoshi',
        sttnAddr: '三重県熊野市井戸町809-3',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '有井',
        ekimeiKana: 'ありい',
        ekimeiRoma: 'Arii',
        sttnAddr: '三重県熊野市有馬町1003',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '神志山',
        ekimeiKana: 'こうしやま',
        ekimeiRoma: 'Kōshiyama',
        sttnAddr: '三重県南牟婁郡御浜町大字下市木4649',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '紀伊市木',
        ekimeiKana: 'きいいちぎ',
        ekimeiRoma: 'Kii-ichigi',
        sttnAddr: '三重県南牟婁郡御浜町大字下市木4489',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '阿田和',
        ekimeiKana: 'あたわ',
        ekimeiRoma: 'Atawa',
        sttnAddr: '三重県南牟婁郡御浜町大字阿田和5114',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '紀伊井田',
        ekimeiKana: 'きいいだ',
        ekimeiRoma: 'Kii-ida',
        sttnAddr: '三重県南牟婁郡紀宝町井田1444',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '鵜殿駅',
        ekimeiKana: 'うどの',
        ekimeiRoma: 'Udono',
        sttnAddr: '三重県南牟婁郡紀宝町鵜殿1551',
        ...JrcKiseihonCommon,
    },
    {
        ekimeiKanj: '新宮',
        ekimeiKana: 'しんぐう',
        ekimeiRoma: 'Shingū',
        sttnAddr: '和歌山県新宮市徐福二丁目1-1',
        ...JrcKiseihonCommon,
    },
];
