const JrcMeishouCommon = {
    ...compNameJrc,
    lineName: '名松線',
    lineBack1: '#f77321',
};

const JrcMeishou = [
    {
        ekimeiKanj: '松阪',
        ekimeiKana: 'まつさか',
        ekimeiRoma: 'Matsusaka',
        sttnAddr: '三重県松阪市京町301',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '上ノ庄',
        ekimeiKana: 'かみのしょう',
        ekimeiRoma: 'Kaminoshō',
        sttnAddr: '三重県松阪市上ノ庄町865',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '権現前',
        ekimeiKana: 'ごんげんまえ',
        ekimeiRoma: 'Gongemmae',
        sttnAddr: '三重県松阪市嬉野権現前町861',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢八太',
        ekimeiKana: 'いせはた',
        ekimeiRoma: 'Ise-hata',
        sttnAddr: '三重県津市一志町小山4',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '一志',
        ekimeiKana: 'いちし',
        ekimeiRoma: 'Ichishi',
        sttnAddr: '三重県津市一志町八太1548',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '井関',
        ekimeiKana: 'いせぎ',
        ekimeiRoma: 'Isegi',
        sttnAddr: '三重県津市一志町井関1340',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢大井',
        ekimeiKana: 'いせおおい',
        ekimeiRoma: 'Ise-ōi',
        sttnAddr: '三重県津市一志町井生638',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢川口',
        ekimeiKana: 'いせかわぐち',
        ekimeiRoma: 'Ise-kawaguchi',
        sttnAddr: '三重県津市白山町川口3274',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '関ノ宮',
        ekimeiKana: 'せきのみや',
        ekimeiRoma: 'Sekinomiya',
        sttnAddr: '三重県津市白山町川口51',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '家城',
        ekimeiKana: 'いえき',
        ekimeiRoma: 'Ieki',
        sttnAddr: '三重県津市白山町南家城874',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢竹原',
        ekimeiKana: 'いせたけはら',
        ekimeiRoma: 'Ise-takehara',
        sttnAddr: '三重県津市美杉町竹原',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢鎌倉',
        ekimeiKana: 'いせかまくら',
        ekimeiRoma: 'Ise-kamakura',
        sttnAddr: '三重県津市美杉町八知',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢八知',
        ekimeiKana: 'いせやち',
        ekimeiRoma: 'Ise-yachi',
        sttnAddr: '三重県津市美杉町八知5767',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '比津',
        ekimeiKana: 'ひつ',
        ekimeiRoma: 'Hitsu',
        sttnAddr: '三重県津市美杉町八知',
        ...JrcMeishouCommon,
    },
    {
        ekimeiKanj: '伊勢奥津',
        ekimeiKana: 'いせおきつ',
        ekimeiRoma: 'Ise-Okitsu',
        sttnAddr: '三重県津市美杉町奥津1288-8',
        ...JrcMeishouCommon,
    },
];
