const SskInaCommon = {
    ...compNameSsk,
    lineName: '伊奈線',
    lineBack1: '#339999',
};

const SskIna = [
    {
        ekimeiKanj: '大宮',
        ekimeiKana: 'おおみや',
        ekimeiRoma: 'Ōmiya',
        sttnAddr: 'さいたま市大宮区錦町685-1',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '鉄道博物館',
        ekimeiKana: 'てつどうはくぶつかん',
        ekimeiRoma: 'The Railway Museum',
        sttnAddr: 'さいたま市大宮区大成町三丁目',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '加茂宮',
        ekimeiKana: 'かものみや',
        ekimeiRoma: 'Kamonomiya',
        sttnAddr: 'さいたま市北区宮原町一丁目',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '東宮原',
        ekimeiKana: 'ひがしみやはら',
        ekimeiRoma: 'Higashi-Miyahara',
        sttnAddr: 'さいたま市北区宮原町二丁目',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '今羽',
        ekimeiKana: 'こんば',
        ekimeiRoma: 'Komba',
        sttnAddr: 'さいたま市北区吉野町一丁目26',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '吉野原',
        ekimeiKana: 'よしのはら',
        ekimeiRoma: 'Yoshinohara',
        sttnAddr: 'さいたま市北区吉野町一丁目',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '原市',
        ekimeiKana: 'はらいち',
        ekimeiRoma: 'Haraichi',
        sttnAddr: '埼玉県上尾市五番町',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '沼南',
        ekimeiKana: 'しょうなん',
        ekimeiRoma: 'Shōnan',
        sttnAddr: '埼玉県上尾市大字原市2135-10',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '丸山',
        ekimeiKana: 'まるやま',
        ekimeiRoma: 'Maruyama',
        sttnAddr: '埼玉県北足立郡伊奈町大字小室',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '志久',
        ekimeiKana: 'しく',
        ekimeiRoma: 'Shiku',
        sttnAddr: '埼玉県北足立郡伊奈町大字小室',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '伊奈中央',
        ekimeiKana: 'いなちゅうおう',
        ekimeiRoma: 'Ina-Chūō',
        sttnAddr: '埼玉県北足立郡伊奈町中央一丁目',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '羽貫',
        ekimeiKana: 'はぬき',
        ekimeiRoma: 'Hanuki',
        sttnAddr: '埼玉県北足立郡伊奈町学園一丁目1番地',
        ...SskInaCommon,
    },
    {
        ekimeiKanj: '内宿',
        ekimeiKana: 'うちじゅく',
        ekimeiRoma: 'Uchijuku',
        sttnAddr: '埼玉県北足立郡伊奈町内宿台三丁目',
        ...SskInaCommon,
    },
];
